/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PFE.GUI;

import static PFE.GUI.updatefacture.AffichToutesfact;
import static PFE.GUI.updatefacture.Affichidfact;
import static PFE.GUI.updatefacture.Affichidfr;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author MOHAMED
 */
public class ajout_modif_facture_fr extends javax.swing.JFrame {

    /**
     * Creates new form ajout_modif_facture_fr
     */
    
    
    
 private  int  var=0;  
 private  Fact fact = new Fact();
 private    String  type_btn;   
 private String   varA;
 private String   varB;
 private  JFileChooser fileChooser = new JFileChooser();
 File selectedFile_ajout_modif_pdt=null;
       
 
    
    
    
    
    
    public ajout_modif_facture_fr(int i,String IdFact,String IdFr,double MontFactFr,String date_t,String image,String  type,String   varA ,String  varB ) {
        initComponents();
        
         txt_idFact.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
         txt_idfr.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
         txt_montant.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
         ( (JTextField)  txt_dateFact1.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));

         
        
        
        
        if(i==1){
        
         txt_idFact.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
         txt_idFact.setEnabled(false);
         txt_idfr.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
         txt_idfr.setEnabled(false);
         txt_idFact.setText(IdFact);
         txt_idfr.setText(IdFr);
         txt_montant.setText(MontFactFr+"");
        ((JTextField)  txt_dateFact1.getDateEditor().getUiComponent()).setText(date_t);
          fileChooser.setSelectedFile(new File(image));
         this.type_btn=type;
         this.varA=varA;
         this.varB=varB;
         
       modifier.setEnabled(true);
       ajouter.setEnabled(false);
       ajouter_autre.setEnabled(false);
    }else{
            
         ajouter.setEnabled(true);
         ajouter_autre.setEnabled(true);

         modifier.setEnabled(false);
        }
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_idfact = new javax.swing.JLabel();
        lb_idFr = new javax.swing.JLabel();
        lb_dateFact1 = new javax.swing.JLabel();
        lb_montant = new javax.swing.JLabel();
        lb_photo = new javax.swing.JLabel();
        txt_idFact = new javax.swing.JTextField();
        txt_idfr = new javax.swing.JTextField();
        txt_montant = new javax.swing.JTextField();
        txt_dateFact1 = new com.toedter.calendar.JDateChooser();
        telecharger = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        fermer = new javax.swing.JButton();
        ajouter_autre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_idfact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_idfact.setText("Identifiant de la Facture : * ");
        getContentPane().add(lb_idfact, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        lb_idFr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_idFr.setText("Identifiant du Fournisseur : *");
        getContentPane().add(lb_idFr, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        lb_dateFact1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_dateFact1.setText("Date de la Facture : * ");
        getContentPane().add(lb_dateFact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        lb_montant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_montant.setText("Montant de la Facture : * ");
        getContentPane().add(lb_montant, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        lb_photo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_photo.setText("Photo de la Facture : ");
        getContentPane().add(lb_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));
        getContentPane().add(txt_idFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 280, 30));
        getContentPane().add(txt_idfr, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 280, 30));

        txt_montant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_montantActionPerformed(evt);
            }
        });
        getContentPane().add(txt_montant, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 280, 30));

        txt_dateFact1.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txt_dateFact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 280, 30));

        telecharger.setText("Parcourir...");
        telecharger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telechargerActionPerformed(evt);
            }
        });
        getContentPane().add(telecharger, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 293, 120, 30));

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        getContentPane().add(ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 100, 30));

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        getContentPane().add(modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 100, 30));

        fermer.setText("Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });
        getContentPane().add(fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 100, 30));

        ajouter_autre.setText("Ajouter des Produits à la Facture");
        ajouter_autre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter_autreActionPerformed(evt);
            }
        });
        getContentPane().add(ajouter_autre, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PFE/GUI/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 522));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
        this.dispose();
    }//GEN-LAST:event_fermerActionPerformed

    private void ajouter_autreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter_autreActionPerformed
    new ajout_modif_produit_in_facture(2,txt_idFact.getText(),null,0.00,0.00,null).setVisible(true);
    
    
    
    
    
    
    
    }//GEN-LAST:event_ajouter_autreActionPerformed

    private void telechargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telechargerActionPerformed
     
        
         fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
         fileChooser.addChoosableFileFilter(filter);
         int result = fileChooser.showSaveDialog(null);
         if(result == JFileChooser.APPROVE_OPTION){
          selectedFile_ajout_modif_pdt= fileChooser.getSelectedFile();     
        
        
        
         }
        
        
        
        
        
        
        
    }//GEN-LAST:event_telechargerActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
        
        
        
 
   
   
   
   
   
   if(txt_idFact.getText().isEmpty()){txt_idFact.setBorder(BorderFactory.createLineBorder(Color.red));}
   if(txt_idfr.getText().isEmpty()){txt_idfr.setBorder(BorderFactory.createLineBorder(Color.red));}
   
   if(txt_montant.getText().isEmpty() ){txt_montant.setBorder(BorderFactory.createLineBorder(Color.red));;}      

   if(!txt_idFact.getText().isEmpty()){txt_idFact.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));}
   if(!txt_idfr.getText().isEmpty()){txt_idfr.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));}
   

  
        
   if(!( (JTextField)  txt_dateFact1.getDateEditor().getUiComponent()).getText().isEmpty() && ((JTextField)  txt_dateFact1.getDateEditor().getUiComponent()).getText().matches("\\d{4}-\\d{2}-\\d{2}")){

       ((JTextField)  txt_dateFact1.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));}
   
  
   
   
   
   
   
   
   if(( (JTextField)  txt_dateFact1.getDateEditor().getUiComponent()).getText().isEmpty() || !((JTextField)  txt_dateFact1.getDateEditor().getUiComponent()).getText().matches("\\d{4}-\\d{2}-\\d{2}")   ){
   ( (JTextField)  txt_dateFact1.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(Color.red));
    var=1;}
  
   
   
   
   
   
   
   
if(!txt_montant.getText().isEmpty()  ){
        
 if(txt_montant.getText().matches("[0-9\\.E]*") || txt_montant.getText().matches("[0-9\\.]*") || txt_montant.getText().matches("[0-9]*") || txt_montant.getText().matches("[0-9E]*")){

     int  pos=txt_montant.getText().indexOf('.');
   
   if(pos!=-1){
       if(txt_montant.getText().indexOf(".",pos+1)!=-1){
        txt_montant.setBorder(BorderFactory.createLineBorder(Color.red));
       return;
       }else{txt_montant.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));}   
    }else{txt_montant.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));}
 }else{
  txt_montant.setBorder(BorderFactory.createLineBorder(Color.red));
  return;  
}      

}
    
    
    
    
  
   if(telecharger.getText().equals("Telecharger")){
    var=1;}   



    
  if(var==1){
      return;
  }  
    
    
    
    
    
    
    
    
   
   if(!txt_idFact.getText().isEmpty() && !txt_idfr.getText().isEmpty() &&  
   !txt_montant.getText().isEmpty()  && !((JTextField)  txt_dateFact1.getDateEditor().getUiComponent()).getText().isEmpty()){
        
           
            if(evt!=null){
             if(selectedFile_ajout_modif_pdt==null){
            fact.AjoutFactFr(new Fact(txt_idFact.getText(), txt_idfr.getText(), ((JTextField)  txt_dateFact1.getDateEditor().getUiComponent()).getText(),Double.parseDouble(txt_montant.getText()),""));
            }else{
            fact.AjoutFactFr(new Fact(txt_idFact.getText(), txt_idfr.getText(), ((JTextField)  txt_dateFact1.getDateEditor().getUiComponent()).getText(),Double.parseDouble(txt_montant.getText()),fileChooser.getSelectedFile().getAbsolutePath()));
            }
            
            
            
   }else{
          if(selectedFile_ajout_modif_pdt!=null){
            fact.Modiffact(new Fact(txt_idFact.getText(), txt_idfr.getText(), ((JTextField)  txt_dateFact1.getDateEditor().getUiComponent()).getText(),Double.parseDouble(txt_montant.getText()),fileChooser.getSelectedFile().getAbsolutePath()));
          }else{
            fact.Modiffact(new Fact(txt_idFact.getText(), txt_idfr.getText(), ((JTextField)  txt_dateFact1.getDateEditor().getUiComponent()).getText(),Double.parseDouble(txt_montant.getText()),""));
          }
            
          if(type_btn.equals("btn1")){
              
              if(varA.equals("IDFact")){
                  updatefacture.Affichidfact(varB);
          }else if(varA.equals("IDFr")){
                  updatefacture.Affichidfr(varB);

          }else if(varA.equals("ToutesFact")){
              updatefacture.AffichToutesfact();

          }      
              
              
              
          }else if(type_btn.equals("btn2")){
              updatefacture.Affichdat(varA,varB);
          } 
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            }





                  var=0;
     
 }
   
   
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_ajouterActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
        ajouterActionPerformed(null);
    }//GEN-LAST:event_modifierActionPerformed

    private void txt_montantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_montantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_montantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_facture_fr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_facture_fr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_facture_fr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_facture_fr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajout_modif_facture_fr(0,null,null,0.00,null,null,null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton ajouter_autre;
    private javax.swing.JButton fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_dateFact1;
    private javax.swing.JLabel lb_idFr;
    private javax.swing.JLabel lb_idfact;
    private javax.swing.JLabel lb_montant;
    private javax.swing.JLabel lb_photo;
    private javax.swing.JButton modifier;
    private javax.swing.JButton telecharger;
    private com.toedter.calendar.JDateChooser txt_dateFact1;
    private javax.swing.JTextField txt_idFact;
    private javax.swing.JTextField txt_idfr;
    private javax.swing.JTextField txt_montant;
    // End of variables declaration//GEN-END:variables
}
