/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PFE.GUI;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.JTableHeader;

/**
 *
 * @author MOHAMED
 */
public class ajout_modif_produit_in_facture extends javax.swing.JFrame {

    /**
     * Creates new form ajout_modif_produit_in_facture
     */
    
    private   FactFrPdt  factfrpdt = new FactFrPdt();
    private String IdPdt;
    private  String IdFcatFr;
    private String typeP;
    public ajout_modif_produit_in_facture(int i,String IdFactFr,String IdPdt,double QteAchatPdt,double PrxAchatPdt,String  typePage) {
        initComponents();
       
         txt_idfactfr.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
         txt_idpdt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
         txt_prixpdt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
         txt_qtepdt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));

      
       if(i==2){
       txt_idfactfr.setText(IdFactFr);
       btn_modifier.setEnabled(false);
       btn_ajouter.setEnabled(true); 
       btn_autreAjouter.setEnabled(true);
       }
        
        if(i==1){ 
            
            
        this.IdPdt=IdPdt;
        this.IdFcatFr=IdFactFr;
        this.typeP=typePage;
        txt_idfactfr.setText(this.IdFcatFr);
        txt_idpdt.setText(this.IdPdt);
        txt_qtepdt.setText(QteAchatPdt+"");
        txt_prixpdt.setText(PrxAchatPdt+"");
         txt_idfactfr.setEnabled(false);
         txt_idfactfr.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));   
         txt_idpdt.setEnabled(false);
         txt_idpdt.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));   
                        
            
            
       btn_autreAjouter.setEnabled(false);
       btn_modifier.setEnabled(true);
       btn_ajouter.setEnabled(false);
    }else{
            
         btn_ajouter.setEnabled(true);
         btn_modifier.setEnabled(false);
        }
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_idfactfr = new javax.swing.JLabel();
        lb_idpdt = new javax.swing.JLabel();
        lb_qtepdt = new javax.swing.JLabel();
        lb_prixpdt = new javax.swing.JLabel();
        txt_idfactfr = new javax.swing.JTextField();
        txt_idpdt = new javax.swing.JTextField();
        txt_qtepdt = new javax.swing.JTextField();
        txt_prixpdt = new javax.swing.JTextField();
        btn_ajouter = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        btn_autreAjouter = new javax.swing.JButton();
        btn_fermer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_idfactfr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_idfactfr.setText("Identifiant de la facture : *");
        getContentPane().add(lb_idfactfr, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        lb_idpdt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_idpdt.setText("Identifiant du produit : *");
        getContentPane().add(lb_idpdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        lb_qtepdt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_qtepdt.setText("Quantité achetée du produit : *");
        getContentPane().add(lb_qtepdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        lb_prixpdt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_prixpdt.setText("Prix d'achat du produit : *");
        getContentPane().add(lb_prixpdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));
        getContentPane().add(txt_idfactfr, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 270, 30));
        getContentPane().add(txt_idpdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 270, 30));
        getContentPane().add(txt_qtepdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 270, 30));
        getContentPane().add(txt_prixpdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 270, 30));

        btn_ajouter.setText("Ajouter un produit à la facture");
        btn_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 230, 40));

        btn_modifier.setText("Modifier un produit dans la facture");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 230, 40));

        btn_autreAjouter.setText("Ajouter un autre produit");
        btn_autreAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_autreAjouterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_autreAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 230, 40));

        btn_fermer.setText("Fermer");
        btn_fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fermerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 230, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PFE/GUI/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 999, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fermerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_fermerActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
        btn_ajouterActionPerformed(null);
    }//GEN-LAST:event_btn_modifierActionPerformed

    private void btn_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouterActionPerformed
        // TODO add your handling code here:
        
        
        
   int   Var=0;
   
   
   
   
   if(txt_idfactfr.getText().isEmpty()){txt_idfactfr.setBorder(BorderFactory.createLineBorder(Color.red));}
   if(txt_idpdt.getText().isEmpty()){txt_idpdt.setBorder(BorderFactory.createLineBorder(Color.red));}
   if(!txt_idfactfr.getText().isEmpty()){txt_idfactfr.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));}
   if(!txt_idpdt.getText().isEmpty()){txt_idpdt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));}      
  
   
   
   
   
 
   if( txt_qtepdt.getText().matches("[0-9\\.E]*") || txt_qtepdt.getText().matches("[0-9\\.]*") || txt_qtepdt.getText().matches("[0-9]*") || txt_qtepdt.getText().matches("[0-9E]*")){txt_qtepdt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223))); }
   else{
       Var=1;
txt_qtepdt.setBorder(BorderFactory.createLineBorder(Color.red));   }
   
   
   
   
   if(txt_prixpdt.getText().matches("[0-9\\.E]*") || txt_prixpdt.getText().matches("[0-9\\.]*") || txt_prixpdt.getText().matches("[0-9]*") || txt_prixpdt.getText().matches("[0-9E]*")){txt_prixpdt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223))); }
   else{
       Var=1;
       txt_prixpdt.setBorder(BorderFactory.createLineBorder(Color.red));
   }
  
 
   if(Var==1){
   return;}

   
   
      
  Var=0;
  int  pos1=txt_prixpdt.getText().indexOf('.');
  int  pos2=txt_qtepdt.getText().indexOf('.');

  if(pos1!=-1){
  if(txt_prixpdt.getText().indexOf(".",pos1+1)!=-1){
  txt_prixpdt.setBorder(BorderFactory.createLineBorder(Color.red));  
   Var=1;}}
  
  if(pos2!=-1){
  if(txt_qtepdt.getText().indexOf(".",pos2+1)!=-1){
  txt_qtepdt.setBorder(BorderFactory.createLineBorder(Color.red));  
   Var=1;}    
  }
  
   if(Var==1){
   return;}

   
   
   
   
   
   
   
   
   
   
   
   
   
 
   
   
   
   
         
  if(!txt_idfactfr.getText().isEmpty() &&  !txt_idpdt.getText().isEmpty() && !txt_qtepdt.getText().isEmpty() && !txt_prixpdt.getText().isEmpty()){
   
      
      
      
  if(evt!=null){    
  factfrpdt.AjoutFactFrPdt(new FactFrPdt(txt_idfactfr.getText(),txt_idpdt.getText(),Double.parseDouble(txt_qtepdt.getText()),Double.parseDouble(txt_prixpdt.getText())));
 }else{
  factfrpdt.ModifFactFrPdt(new FactFrPdt(txt_idfactfr.getText(),txt_idpdt.getText(),Double.parseDouble(txt_qtepdt.getText()),Double.parseDouble(txt_prixpdt.getText())));
  
  
 if(typeP.equals("rech_pdt_in_facture")){
     rech_pdt_in_facture.AffichIdPdtIdFactFr(IdFcatFr, IdPdt);
 
 }
 else if(typeP.equals("rechall")){
    rechall.AffichToutesFactFrPdt();
 
 } else if(typeP.equals("rech_facture_in_pdt")){
    rech_facture_in_pdt.AffichPrxAchatPdt(IdPdt);
 }else if(typeP.equals("rech_all_pdt_in_facture")){
 rech_all_pdt_in_facture.AffichIdFactFrPdt(IdFcatFr);
 }
  
  
  
  }
  
  
  
  
  
  
  
  
 txt_idfactfr.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
 txt_idpdt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
 txt_prixpdt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
 txt_qtepdt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
 

  }
   
   
   
   
   
   
   
   
   
 
   
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btn_ajouterActionPerformed

    private void btn_autreAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_autreAjouterActionPerformed
        // TODO add your handling code here:
        
        txt_idfactfr.setEnabled(true);
        txt_idpdt.setEnabled(true);
        
        btn_modifier.setEnabled(false);
        btn_ajouter.setEnabled(true);
        btn_autreAjouter.setEnabled(true);
        txt_idpdt.setText("");
        txt_prixpdt.setText("");
        txt_qtepdt.setText("");
        
        
    }//GEN-LAST:event_btn_autreAjouterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_produit_in_facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_produit_in_facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_produit_in_facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_produit_in_facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajout_modif_produit_in_facture(0,null,null,0.00,0.00,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajouter;
    private javax.swing.JButton btn_autreAjouter;
    private javax.swing.JButton btn_fermer;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_idfactfr;
    private javax.swing.JLabel lb_idpdt;
    private javax.swing.JLabel lb_prixpdt;
    private javax.swing.JLabel lb_qtepdt;
    private javax.swing.JTextField txt_idfactfr;
    private javax.swing.JTextField txt_idpdt;
    private javax.swing.JTextField txt_prixpdt;
    private javax.swing.JTextField txt_qtepdt;
    // End of variables declaration//GEN-END:variables
}
