/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PFE.GUI;

import static PFE.GUI.updatefr.AffichIdFr;
import java.awt.Color;
import java.awt.Event;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author MOHAMED
 */
public class ajout_modif_fr extends javax.swing.JFrame {

    /**
     * Creates new form ajout_modif_fr
     */
    
    
 

private  String  IdFr;
private  String  NomFr;
private  String  CategFr;
private  String  Tel1 ;
private  String  Tel2 ;
private  String  Fax1 ;
private  String  Fax2 ;
private  String  adresse ;
private  String  saisir ;
private  String  list_item ;
private  Fournisseur   fr=null ;


   private   int  var=0;
    
    
    public ajout_modif_fr(int i,String IdFr,String NomFr,String CategFr,String Tel1,String Tel2,String Fax1,String Fax2,String adresse,String list_item,String saisir ) {
        
    initComponents();
    fr=new Fournisseur();


txt_id.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
txt_nom.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
txt_fax1.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
txt_fax2.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
txt_adresse.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
txt_tel1.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
txt_tel2.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
        
        
       
        
        
        
        
        
        
        
        
        
        
        
        
      if(i==0){
                Ajouter.setEnabled(true);
                modifier.setEnabled(false);
  
      }else{
          
          
        
        
        txt_id.setText(IdFr);
        txt_id.setEnabled(false);
        txt_nom.setText(NomFr);
        
        if(CategFr.equals("Alimentation")){

                        txt_list.setSelectedIndex(0);

                    }
                    if(CategFr.equals("Boisson")){
                        txt_list.setSelectedIndex(1);

                    }
                    if(CategFr.equals("Electronics")){
                        txt_list.setSelectedIndex(2);

                    }
                    if(CategFr.equals("Habillement")){
                        txt_list.setSelectedIndex(3);

                    }  
        
        
        
        
        
        
        
        this.list_item=list_item;
        this.saisir=saisir;
        
        
        txt_tel1.setText(Tel1);
        txt_tel2.setText(Tel2);
        txt_fax1.setText(Fax1);
        txt_fax2.setText(Fax2);
        txt_adresse.setText(adresse);
          
          
          
          
               modifier.setEnabled(true);
               Ajouter.setEnabled(false);
      }
        
        
        
        
    }

   
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_id = new javax.swing.JLabel();
        lb_nom = new javax.swing.JLabel();
        lb_categ = new javax.swing.JLabel();
        lb_tel1 = new javax.swing.JLabel();
        lb_tel2 = new javax.swing.JLabel();
        lb_fax1 = new javax.swing.JLabel();
        lb_fax2 = new javax.swing.JLabel();
        lb_adresse = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        txt_tel1 = new javax.swing.JTextField();
        txt_tel2 = new javax.swing.JTextField();
        txt_fax1 = new javax.swing.JTextField();
        txt_fax2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_adresse = new javax.swing.JTextArea();
        Ajouter = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        fermer = new javax.swing.JButton();
        txt_list = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_id.setText("Identifiant du Fournisseur : *");
        getContentPane().add(lb_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 210, 30));

        lb_nom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_nom.setText("Nom du Fournisseur : * ");
        getContentPane().add(lb_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 190, -1));

        lb_categ.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_categ.setText("Catégorie du Fournisseur : *");
        getContentPane().add(lb_categ, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 190, -1));

        lb_tel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_tel1.setText("Téléphone 1 du Fournisseur : *");
        getContentPane().add(lb_tel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 210, -1));

        lb_tel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_tel2.setText("Téléphone 2 du Fournisseur : ");
        getContentPane().add(lb_tel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 210, -1));

        lb_fax1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_fax1.setText("Fax 1 du Fournisseur : ");
        getContentPane().add(lb_fax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 210, -1));

        lb_fax2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_fax2.setText("Fax 2 du Fournisseur : ");
        getContentPane().add(lb_fax2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 190, -1));

        lb_adresse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_adresse.setText("Adresse : *");
        getContentPane().add(lb_adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 110, -1));
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 270, 30));
        getContentPane().add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 270, 30));

        txt_tel1.setToolTipText("");
        txt_tel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tel1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_tel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 270, 30));
        getContentPane().add(txt_tel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 270, 30));
        getContentPane().add(txt_fax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 270, 30));

        txt_fax2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fax2ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_fax2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 270, 30));

        txt_adresse.setColumns(20);
        txt_adresse.setRows(5);
        jScrollPane1.setViewportView(txt_adresse);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 270, -1));

        Ajouter.setText("Ajouter");
        Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterActionPerformed(evt);
            }
        });
        getContentPane().add(Ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 120, 40));

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        getContentPane().add(modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 120, 40));

        fermer.setText("Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });
        getContentPane().add(fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, 120, 40));

        txt_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentation", "Boisson", "Electronics", "Habillement" }));
        getContentPane().add(txt_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 270, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PFE/GUI/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 1000, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fax2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fax2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fax2ActionPerformed

    private void txt_tel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tel1ActionPerformed

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
        this.dispose();
        
        
        
    }//GEN-LAST:event_fermerActionPerformed

    private void AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterActionPerformed
     
        

        
        
        
        IdFr=txt_id.getText();
        NomFr=txt_nom.getText();
        CategFr=(String) txt_list.getSelectedItem();
        Tel1 =txt_tel1.getText();
        Tel2 =txt_tel2.getText();
        Fax1 =txt_fax1.getText();
        Fax2 =txt_fax2.getText();
        adresse =txt_adresse.getText();
        
        
        



        if(txt_id.getText().isEmpty()){txt_id.setBorder(BorderFactory.createLineBorder(Color.red));}
        if(!txt_id.getText().isEmpty()){txt_id.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));}
        if(txt_nom.getText().isEmpty()){txt_nom.setBorder(BorderFactory.createLineBorder(Color.red));}
        if(!txt_nom.getText().isEmpty()){txt_nom.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));}
        if(txt_tel1.getText().isEmpty()){txt_tel1.setBorder(BorderFactory.createLineBorder(Color.red));}
        if(!txt_tel1.getText().isEmpty()){txt_tel1.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));}
        if(txt_adresse.getText().isEmpty()){txt_adresse.setBorder(BorderFactory.createLineBorder(Color.red));}
        if(!txt_adresse.getText().isEmpty()){txt_adresse.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));}

        if(!Tel1.isEmpty() ||  !Tel2.isEmpty() || !Fax1.isEmpty() || !Fax2.isEmpty()){

            if(!Tel1.matches("[0-9]*")){
                txt_tel1.setBorder(BorderFactory.createLineBorder(Color.red));
                var=1;}
            if(Tel1.matches("[0-9]*")){
                txt_tel1.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
            }

            if(!Tel2.matches("[0-9]*")){
                txt_tel2.setBorder(BorderFactory.createLineBorder(Color.red));
                var=1;}
            if(Tel2.matches("[0-9]*")){
                txt_tel2.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
            }

            if(!Fax1.matches("[0-9]*") ){
                txt_fax1.setBorder(BorderFactory.createLineBorder(Color.red));
                var=1;}
            if(Fax1.matches("[0-9]*") ){
                txt_fax1.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
            }

            if(!Fax2.matches("[0-9]*") ){
                txt_fax2.setBorder(BorderFactory.createLineBorder(Color.red));
                var=1;}

            if(Fax2.matches("[0-9]*" ) ){
                txt_fax2.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
            }

            if(var==1){
                var=0;
                return;
            }

        }

 if( (!txt_id.getText().isEmpty()  &&  !txt_nom.getText().isEmpty()   &&  
      !txt_adresse.getText().isEmpty()&&  !txt_tel1.getText().isEmpty() )){
            
            
            if(evt!=null){
            fr.AjoutFr(new Fournisseur(IdFr, NomFr, CategFr, Tel1, Tel2, Fax1, Fax2, adresse));            
            }else{
            fr.ModifFr(new Fournisseur(IdFr, NomFr, CategFr, Tel1, Tel2, Fax1, Fax2, adresse));



                if(list_item.equals("Id Fr")){
                    updatefr.AffichIdFr(saisir);                
                }else if(list_item.equals("Nom Fr")){
                    updatefr.AffichNomFr(saisir);
                }else if(list_item.equals("Categorie Fr")){
                   updatefr.AffichCategFr(saisir);
                }else if(list_item.equals("Toutes Fr")){
                   updatefr.AffichToutesFr();
                }


            
            }        
             
                
          
        }
    
    
    
    
    
    
    
    
    
    
    
    
      
    
    }//GEN-LAST:event_AjouterActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
     AjouterActionPerformed(null);   
     
     
     
     
    }//GEN-LAST:event_modifierActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_formWindowOpened

    

    

   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_fr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_fr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_fr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_fr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
       //      new ajout_modif_fr(0,null,null,null,null,null,null,null,null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter;
    private javax.swing.JButton fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_adresse;
    private javax.swing.JLabel lb_categ;
    private javax.swing.JLabel lb_fax1;
    private javax.swing.JLabel lb_fax2;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_nom;
    private javax.swing.JLabel lb_tel1;
    private javax.swing.JLabel lb_tel2;
    private javax.swing.JButton modifier;
    private javax.swing.JTextArea txt_adresse;
    private javax.swing.JTextField txt_fax1;
    private javax.swing.JTextField txt_fax2;
    private javax.swing.JTextField txt_id;
    private javax.swing.JComboBox<String> txt_list;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_tel1;
    private javax.swing.JTextField txt_tel2;
    // End of variables declaration//GEN-END:variables
}
