/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PFE.GUI;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MOHAMED
 */
public class ajout_modif_clt extends javax.swing.JFrame {

    /**
     * Creates new form ajout_modif_clt
     */
    
   
    
    private   Clt  clt = new Clt();
   
   private String  IdClt;
   private String  NomClt;
   private String  Tel1Clt;
   private String  Tel2Clt;
   private String  Fax1Clt;
   private String  Fax2Clt;
   private String  AdrClt;   
   private   String list_item;
   private   String  saisir;
    public ajout_modif_clt(int i,String IdClt,String NomClt,String Tel1Clt,String Tel2Clt,String Fax1Clt,String Fax2Clt,String AdrClt,String  list_item ,String   saisir) {
        initComponents();
        
        
        
txt_idclt.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
txt_nom.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
txt_tel1.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
txt_tel2.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
txt_fax2.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
txt_fax1.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
txt_adresse.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
        
        
        
        






















        
        
            
        
        
        
        
        
        
        
        
        
        
        
      if(i==0){
                ajouter.setEnabled(true);
                modifier.setEnabled(false);
                
                
                
                
                
  
      }else{
          
          
        
        this.list_item=list_item;
        this.saisir=saisir;
        txt_idclt.setText(IdClt);
        txt_idclt.setEditable(false);
        txt_nom.setText(NomClt);
        txt_tel1.setText(Tel1Clt);
        txt_tel2.setText(Tel2Clt);
        txt_fax1.setText(Fax1Clt);
        txt_fax2.setText(Fax2Clt);
        txt_adresse.setText(AdrClt);
 
        modifier.setEnabled(true);
        ajouter.setEnabled(false);
      }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_idclt = new javax.swing.JLabel();
        lb_nom = new javax.swing.JLabel();
        lb_tel1 = new javax.swing.JLabel();
        tel2 = new javax.swing.JLabel();
        lb_fax1 = new javax.swing.JLabel();
        lb_fax2 = new javax.swing.JLabel();
        lb_adresse = new javax.swing.JLabel();
        txt_idclt = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        txt_tel1 = new javax.swing.JTextField();
        txt_tel2 = new javax.swing.JTextField();
        txt_fax1 = new javax.swing.JTextField();
        txt_fax2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_adresse = new javax.swing.JTextArea();
        fermer = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_idclt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_idclt.setText("Identifiant du client : * ");
        getContentPane().add(lb_idclt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, 30));

        lb_nom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_nom.setText("Nom du client : * ");
        getContentPane().add(lb_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, 30));

        lb_tel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_tel1.setText("Téléphone 1 du client : * ");
        getContentPane().add(lb_tel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        tel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tel2.setText("Téléphone 2 du client : ");
        getContentPane().add(tel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        lb_fax1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_fax1.setText("Fax 1 du client : ");
        getContentPane().add(lb_fax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        lb_fax2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_fax2.setText("Fax 2 du client : ");
        getContentPane().add(lb_fax2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        lb_adresse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_adresse.setText("Adresse du client : ");
        getContentPane().add(lb_adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));
        getContentPane().add(txt_idclt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 240, 30));
        getContentPane().add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 240, 30));
        getContentPane().add(txt_tel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 240, 30));
        getContentPane().add(txt_tel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 240, 30));
        getContentPane().add(txt_fax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 240, 30));
        getContentPane().add(txt_fax2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 240, 30));

        txt_adresse.setColumns(20);
        txt_adresse.setRows(5);
        jScrollPane1.setViewportView(txt_adresse);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 240, 100));

        fermer.setText("Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });
        getContentPane().add(fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 120, 40));

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        getContentPane().add(modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 120, 40));

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        getContentPane().add(ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 120, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PFE/GUI/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 900, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
     this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_fermerActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:

        int  var=0;
        
        IdClt=txt_idclt.getText();
        NomClt=txt_nom.getText();
        Tel1Clt =txt_tel1.getText();
        Tel2Clt =txt_tel2.getText();
        Fax1Clt =txt_fax1.getText();
        Fax2Clt =txt_fax2.getText();
        AdrClt =txt_adresse.getText();
        
        
        
        //  pour      designer
        if(txt_idclt.getText().isEmpty()){txt_idclt.setBorder(BorderFactory.createLineBorder(Color.red));}
        if(!txt_idclt.getText().isEmpty()){txt_idclt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));}
        if(txt_nom.getText().isEmpty()){txt_nom.setBorder(BorderFactory.createLineBorder(Color.red));}
        if(!txt_nom.getText().isEmpty()){txt_nom.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));}
        if(txt_tel1.getText().isEmpty()){txt_tel1.setBorder(BorderFactory.createLineBorder(Color.red));}
        if(!txt_tel1.getText().isEmpty()){txt_tel1.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));}
        if(txt_adresse.getText().isEmpty()){txt_adresse.setBorder(BorderFactory.createLineBorder(Color.red));}
        if(!txt_adresse.getText().isEmpty()){txt_adresse.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));}

        if(!Tel1Clt.isEmpty() ||  !Tel2Clt.isEmpty() || !Fax1Clt.isEmpty() || !Fax2Clt.isEmpty()){

            if(!Tel1Clt.matches("[0-9]*")){
                txt_tel1.setBorder(BorderFactory.createLineBorder(Color.red));
                var=1;}
            if(Tel1Clt.matches("[0-9]*")){
                txt_tel1.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
            }

            if(!Tel2Clt.matches("[0-9]*")){
                txt_tel2.setBorder(BorderFactory.createLineBorder(Color.red));
                var=1;}
            if(Tel2Clt.matches("[0-9]*")){
                txt_tel2.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
            }

            if(!Fax1Clt.matches("[0-9]*") ){
                txt_fax1.setBorder(BorderFactory.createLineBorder(Color.red));
                var=1;}
            if(Fax1Clt.matches("[0-9]*") ){
                txt_fax1.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
            }

            if(!Fax2Clt.matches("[0-9]*") ){
                txt_fax2.setBorder(BorderFactory.createLineBorder(Color.red));
                var=1;}

            if(Fax2Clt.matches("[0-9]*" ) ){
                txt_fax2.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
            }

            if(var==1){
                var=0;
                return;
            }

        }

        if( (!txt_idclt.getText().isEmpty()  && !txt_nom.getText().isEmpty()&&  !txt_adresse.getText().isEmpty()   &&  !txt_tel1.getText().isEmpty() )){
            
            
            if(evt!=null){
            
            
               if(clt.AjoutClt(new Clt(IdClt, NomClt,Tel1Clt,Tel2Clt, Fax1Clt, Fax2Clt,AdrClt))!=null) {
                  }}
            else{
                
                
          clt.ModifClt(new Clt(IdClt, NomClt,Tel1Clt,Tel2Clt, Fax1Clt, Fax2Clt,AdrClt));
               
          if(list_item.equals("Id Clt")){
              updateclt.AffichIdClt(saisir);
          }else if(list_item.equals("Nom Clt")){
            updateclt.AffichNomClt(saisir);

            }else if(list_item.equals("Toutes Clt")){
             updateclt.AffichTousClt();

            }
          
               
               
               
               
               
               
                          
                
                
            }
            
            
            
            
            
        }
    
    
    
    
    
      
     
        
    }//GEN-LAST:event_ajouterActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
      ajouterActionPerformed(null);    
    }//GEN-LAST:event_modifierActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    
      

    
    
  
    
    
    
    
  
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_clt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_clt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_clt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_clt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajout_modif_clt(0,null,null,null,null,null,null,null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_adresse;
    private javax.swing.JLabel lb_fax1;
    private javax.swing.JLabel lb_fax2;
    private javax.swing.JLabel lb_idclt;
    private javax.swing.JLabel lb_nom;
    private javax.swing.JLabel lb_tel1;
    private javax.swing.JButton modifier;
    private javax.swing.JLabel tel2;
    private javax.swing.JTextArea txt_adresse;
    private javax.swing.JTextField txt_fax1;
    private javax.swing.JTextField txt_fax2;
    private javax.swing.JTextField txt_idclt;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_tel1;
    private javax.swing.JTextField txt_tel2;
    // End of variables declaration//GEN-END:variables
}
