/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PFE.GUI;

import java.awt.Color;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author MOHAMED
 */
public class ajout_modif_cmd_clt extends javax.swing.JFrame {

    /**
     * Creates new form ajout_modif_cmd_clt
     */
    
    
    
    private  String    IdCmdClt;
    private  String    IdClt;
    private  double    AvanceCmdClt;
    private  String    Prop1CmdClt;
    private  String    Prop2CmdClt;
    private  String    DateCmdClt;
    private  String    PhotoCmdClt;
    private  String Type;
    private  JFileChooser fileChooser = new JFileChooser();
    File selectedFile_ajout_modif_pdt=null;
    private  CmdClt  cmdclt = new CmdClt();
    
    
    
    
    
    
    
    
    public ajout_modif_cmd_clt(int i,String  IdCmdClt,String IdClt,double AvanceCmdClt,String Prop1CmdClt,String Prop2CmdClt,String DateCmdClt,String PhotoCmdClt,String  Type  ) {

 initComponents();
txt_IdCmdClt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
txt_IdClt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
txt_AvanceCmdClt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
txt_Prop1CmdClt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
txt_Prop2CmdClt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
((JTextField) txt_DateCmdClt.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
        
        
       
   
      if(i==0){
                ajouter.setEnabled(true);
                modifier.setEnabled(false);
                ajouter.setEnabled(true);
  
      }else{
          
          
        
        
        txt_IdClt.setEnabled(false);
        txt_IdCmdClt.setEnabled(false);

        
          
        
        
        
        
        
        
        
        
        this.Type=Type;
        txt_IdCmdClt.setText(IdCmdClt);
        txt_IdClt.setText(IdClt);
        txt_AvanceCmdClt.setText(AvanceCmdClt+"");
        txt_Prop1CmdClt.setText(Prop1CmdClt);
        txt_Prop2CmdClt.setText(Prop2CmdClt);
       ((JTextField) txt_DateCmdClt.getDateEditor().getUiComponent()).setText(DateCmdClt);
      
       fileChooser.setSelectedFile(new File(PhotoCmdClt));
       
          
          
          
               modifier.setEnabled(true);
               ajouter.setEnabled(false);
               ajouter_autre.setEnabled(false);
      }
        
        
        
        
    

   

















    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_idcmdclt = new javax.swing.JLabel();
        lb_idclt = new javax.swing.JLabel();
        lb_AvanceCmdClt = new javax.swing.JLabel();
        lb_Prop1CmdClt = new javax.swing.JLabel();
        lb_Prop2CmdClt = new javax.swing.JLabel();
        lb_DateCmdClt = new javax.swing.JLabel();
        lb_PhotoCmdClt = new javax.swing.JLabel();
        txt_IdClt = new javax.swing.JTextField();
        txt_IdCmdClt = new javax.swing.JTextField();
        txt_AvanceCmdClt = new javax.swing.JTextField();
        txt_Prop1CmdClt = new javax.swing.JTextField();
        txt_Prop2CmdClt = new javax.swing.JTextField();
        txt_DateCmdClt = new com.toedter.calendar.JDateChooser();
        telecharger = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        fermer = new javax.swing.JButton();
        ajouter_autre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_idcmdclt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_idcmdclt.setText("Identifiant de la commande du client : *");
        getContentPane().add(lb_idcmdclt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        lb_idclt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_idclt.setText("Identifiant du client : *");
        getContentPane().add(lb_idclt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        lb_AvanceCmdClt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_AvanceCmdClt.setText("Avance de la commande du client : ");
        getContentPane().add(lb_AvanceCmdClt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        lb_Prop1CmdClt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_Prop1CmdClt.setText("Propriété 1 de la commande du client : ");
        getContentPane().add(lb_Prop1CmdClt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        lb_Prop2CmdClt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_Prop2CmdClt.setText("Propriété 2 de la commande du client : ");
        getContentPane().add(lb_Prop2CmdClt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        lb_DateCmdClt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_DateCmdClt.setText("Date de la commande du client : ");
        getContentPane().add(lb_DateCmdClt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        lb_PhotoCmdClt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_PhotoCmdClt.setText("Photo de la commande du client : ");
        getContentPane().add(lb_PhotoCmdClt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));
        getContentPane().add(txt_IdClt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 250, 30));
        getContentPane().add(txt_IdCmdClt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 250, 30));
        getContentPane().add(txt_AvanceCmdClt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 250, 30));
        getContentPane().add(txt_Prop1CmdClt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 250, 30));
        getContentPane().add(txt_Prop2CmdClt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 250, 30));

        txt_DateCmdClt.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txt_DateCmdClt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 290, 30));

        telecharger.setText("Parcourir...");
        telecharger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telechargerActionPerformed(evt);
            }
        });
        getContentPane().add(telecharger, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 110, 30));

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        getContentPane().add(ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 130, 40));

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        getContentPane().add(modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 130, 40));

        fermer.setText("Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });
        getContentPane().add(fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 130, 40));

        ajouter_autre.setText("Ajouter des produits à la commande");
        ajouter_autre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter_autreActionPerformed(evt);
            }
        });
        getContentPane().add(ajouter_autre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PFE/GUI/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 964, 513));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_fermerActionPerformed

    private void ajouter_autreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter_autreActionPerformed
     new ajout_modif_pdt_incmd_fr(0).setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_ajouter_autreActionPerformed

    private void telechargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telechargerActionPerformed
         fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
         fileChooser.addChoosableFileFilter(filter);
         int result = fileChooser.showSaveDialog(null);
         if(result == JFileChooser.APPROVE_OPTION){
          selectedFile_ajout_modif_pdt= fileChooser.getSelectedFile();        
    }

    }//GEN-LAST:event_telechargerActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
   int  a=0;
        
   if(txt_IdClt.getText().isEmpty()){
      a=1;
     txt_IdClt.setBorder(BorderFactory.createLineBorder(Color.red));}
   if(txt_IdCmdClt.getText().isEmpty()){
       a=1;
       txt_IdCmdClt.setBorder(BorderFactory.createLineBorder(Color.red));}
   if(((JTextField) txt_DateCmdClt.getDateEditor().getUiComponent()).getText().isEmpty()){
       a=1;
   ((JTextField) txt_DateCmdClt.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(Color.red));}
   if(!txt_IdClt.getText().isEmpty()){txt_IdClt.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));}
   if(!txt_IdCmdClt.getText().isEmpty()){txt_IdCmdClt.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));}
   if(!((JTextField) txt_DateCmdClt.getDateEditor().getUiComponent()).getText().isEmpty()){((JTextField) txt_DateCmdClt.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));}
      
        
 if(a==1){return ;}

 
 if(!txt_AvanceCmdClt.getText().isEmpty()  ){
        
 if(txt_AvanceCmdClt.getText().matches("[0-9\\.E]*") || txt_AvanceCmdClt.getText().matches("[0-9\\.]*") || txt_AvanceCmdClt.getText().matches("[0-9]*") || txt_AvanceCmdClt.getText().matches("[0-9E]*")){
         
   int  pos=txt_AvanceCmdClt.getText().indexOf('.');
   if(pos!=-1){
       if(txt_AvanceCmdClt.getText().indexOf(".",pos+1)!=-1){
       txt_AvanceCmdClt.setBorder(BorderFactory.createLineBorder(Color.red));
       return;
       }else{txt_AvanceCmdClt.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));}   
    }else{txt_AvanceCmdClt.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));}
 }else{
  txt_AvanceCmdClt.setBorder(BorderFactory.createLineBorder(Color.red));
  return;  
}      

}
 
 
 
 
 
 
 
 
 
 


 
 
 if(evt!=null){

      if(selectedFile_ajout_modif_pdt!=null){
      cmdclt.AjoutCmdClt(new CmdClt(txt_IdCmdClt.getText(), txt_IdClt.getText(),Double.parseDouble(txt_AvanceCmdClt.getText()), txt_Prop1CmdClt.getText(), txt_Prop2CmdClt.getText(),((JTextField) txt_DateCmdClt.getDateEditor().getUiComponent()).getText(),fileChooser.getSelectedFile().getAbsolutePath()));
      }else{
      cmdclt.AjoutCmdClt(new CmdClt(txt_IdCmdClt.getText(), txt_IdClt.getText(),Double.parseDouble(txt_AvanceCmdClt.getText()), txt_Prop1CmdClt.getText(), txt_Prop2CmdClt.getText(),((JTextField) txt_DateCmdClt.getDateEditor().getUiComponent()).getText(),""));
            } 
     
     
 }else{

    if(selectedFile_ajout_modif_pdt!=null){

 cmdclt.ModifCmdClt(new CmdClt(txt_IdCmdClt.getText(), txt_IdClt.getText(),Double.parseDouble(txt_AvanceCmdClt.getText()),txt_Prop1CmdClt.getText(), txt_Prop2CmdClt.getText(),((JTextField) txt_DateCmdClt.getDateEditor().getUiComponent()).getText(),fileChooser.getSelectedFile().getAbsolutePath()));
               }else{

 cmdclt.ModifCmdClt(new CmdClt(txt_IdCmdClt.getText(), txt_IdClt.getText(),Double.parseDouble(txt_AvanceCmdClt.getText()),txt_Prop1CmdClt.getText(), txt_Prop2CmdClt.getText(),((JTextField) txt_DateCmdClt.getDateEditor().getUiComponent()).getText(),""));
 
     
    }
     
 
 
 if(Type.equals("rech_cmd_clt1")){
   rech_cmd_clt1.AffichIdCmdClt(txt_IdCmdClt.getText());
   
 }else if(Type.equals("rech_cmd_clt3")){
     rech_cmd_clt3.AffichCmdClt(txt_IdClt.getText());
}else if(Type.equals("rech_cmd_clt2")){
     System.out.println("PFE.GUI.ajout_modif_cmd_clt.ajouterActionPerformed()");
     rech_cmd_clt2.AffichDateCmdClt(rech_cmd_clt2.Datedebut,rech_cmd_clt2.DateFin);
}else if(Type.equals("rech_cmd_clt5")){
    rech_cmd_clt5.AffichAvanceCmdCltNonNull();
 }else if(Type.equals("rech_cmd_clt7")){
     rech_cmd_clt7.AffichToutesCmdClt();
 }else if(Type.equals("rech_cmd_clt4")){
     rech_cmd_clt4.AffichToutesInfoCmdClt(rech_cmd_clt4.Datedebut,rech_cmd_clt4.DateFin);
 }else if(Type.equals("rech_cmd_clt6")){
     rech_cmd_clt6.AffichDesigPdtQteCmdClt(rech_cmd_clt6.Datedebut,rech_cmd_clt6.DateFin);
 }




 



            
            }      
             
                
          
        
    
    
    
    
    
    
    
    
    
    
 
 
 
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_ajouterActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
        ajouterActionPerformed(null);
        
        
        
        
        
        
    }//GEN-LAST:event_modifierActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_cmd_clt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_cmd_clt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_cmd_clt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_cmd_clt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajout_modif_cmd_clt(0,null,null,0,null,null,null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton ajouter_autre;
    private javax.swing.JButton fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_AvanceCmdClt;
    private javax.swing.JLabel lb_DateCmdClt;
    private javax.swing.JLabel lb_PhotoCmdClt;
    private javax.swing.JLabel lb_Prop1CmdClt;
    private javax.swing.JLabel lb_Prop2CmdClt;
    private javax.swing.JLabel lb_idclt;
    private javax.swing.JLabel lb_idcmdclt;
    private javax.swing.JButton modifier;
    private javax.swing.JButton telecharger;
    private javax.swing.JTextField txt_AvanceCmdClt;
    private com.toedter.calendar.JDateChooser txt_DateCmdClt;
    private javax.swing.JTextField txt_IdClt;
    private javax.swing.JTextField txt_IdCmdClt;
    private javax.swing.JTextField txt_Prop1CmdClt;
    private javax.swing.JTextField txt_Prop2CmdClt;
    // End of variables declaration//GEN-END:variables
}
