/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PFE.GUI;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JTextField;

/**
 *
 * @author MOHAMED
 */
public class ajout_modif_pdt_cmd_clt extends javax.swing.JFrame {

    /**
     * Creates new form ajout_modif_pdt_cmd_clt
     */
    
    private   CmdCltPrd  cmdcltpdt = new CmdCltPrd();
    private String  IdCmdClt;
    private  String IdPdt;
    private  double QteCmdClt;
    private  String  type;

    
    
    
    
    public ajout_modif_pdt_cmd_clt(int i,String  IdCmdClt,String IdPdt,double QteCmdClt,String type) {
        initComponents();
        txt_idcmdclt.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
        txt_idpdt.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
        txt_qte.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
       
        
     
        if(i==1){ 
            
            
        this.IdPdt=IdPdt;
        this.IdCmdClt=IdCmdClt;
        this.QteCmdClt=QteCmdClt;
        this.type=type;
        txt_idcmdclt.setText(this.IdCmdClt);
        txt_idpdt.setText(this.IdPdt);
        txt_qte.setText(this.QteCmdClt+"");
        txt_idcmdclt.setEnabled(false);
        txt_idpdt.setEnabled(false);
            
            
            
       ajouter.setEnabled(false);
       modifier.setEnabled(true);
       ajouter_produit.setEnabled(false);
    }else{
            
         ajouter.setEnabled(true);
         modifier.setEnabled(false);
         ajouter_produit.setEnabled(true);
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_idcmdclt = new javax.swing.JLabel();
        lb_idpdt = new javax.swing.JLabel();
        lb_qte = new javax.swing.JLabel();
        txt_idcmdclt = new javax.swing.JTextField();
        txt_idpdt = new javax.swing.JTextField();
        txt_qte = new javax.swing.JTextField();
        ajouter = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        fermer = new javax.swing.JButton();
        ajouter_produit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_idcmdclt.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lb_idcmdclt.setText("Identifiant de la commande à un Client : * ");
        getContentPane().add(lb_idcmdclt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 290, 30));

        lb_idpdt.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lb_idpdt.setText("Identifiant du produit : * ");
        getContentPane().add(lb_idpdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 190, 60));

        lb_qte.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lb_qte.setText("Quantité de la commande : *");
        getContentPane().add(lb_qte, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 190, 60));
        getContentPane().add(txt_idcmdclt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 350, 40));

        txt_idpdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idpdtActionPerformed(evt);
            }
        });
        getContentPane().add(txt_idpdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 350, 40));

        txt_qte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qteActionPerformed(evt);
            }
        });
        getContentPane().add(txt_qte, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 350, 40));

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        getContentPane().add(ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 130, 40));

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        getContentPane().add(modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 130, 40));

        fermer.setText("Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });
        getContentPane().add(fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 130, 40));

        ajouter_produit.setText("Ajouter un autre produit à la commande");
        ajouter_produit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter_produitActionPerformed(evt);
            }
        });
        getContentPane().add(ajouter_produit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 270, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PFE/GUI/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_qteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qteActionPerformed

    private void txt_idpdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idpdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idpdtActionPerformed

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
        this.dispose();
    }//GEN-LAST:event_fermerActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
        
     int  var=0;
        
   if(txt_idcmdclt.getText().isEmpty()){
       
       var=1;
       txt_idcmdclt.setBorder(BorderFactory.createLineBorder(Color.red));}
   if(txt_idpdt.getText().isEmpty()){
       var=1;
       txt_idpdt.setBorder(BorderFactory.createLineBorder(Color.red));}
   
   if(txt_qte.getText().isEmpty() ){
       var=1;
       txt_qte.setBorder(BorderFactory.createLineBorder(Color.red));;}      

        
      if(!txt_idcmdclt.getText().isEmpty()){txt_idcmdclt.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));}
      if(!txt_idpdt.getText().isEmpty()){txt_idpdt.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));}
         
        
        
      
if(!txt_qte.getText().isEmpty()  ){
        
 if(txt_qte.getText().matches("[0-9\\.E]*") || txt_qte.getText().matches("[0-9\\.]*") || txt_qte.getText().matches("[0-9]*")){
     int  pos=txt_qte.getText().indexOf('.');
   
   if(pos!=-1){
       if(txt_qte.getText().indexOf(".",pos+1)!=-1){
       txt_qte.setBorder(BorderFactory.createLineBorder(Color.red));
       var=1;
       }else{txt_qte.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));}   
    }else{txt_qte.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));}
 }else{
  txt_qte.setBorder(BorderFactory.createLineBorder(Color.red));
       var=1;
}      

}
        
        
        
    if(var==1){
        return;
    }    
        
        
        
        
    if(evt!=null){
     cmdcltpdt.AjoutClt(new CmdCltPrd(txt_idcmdclt.getText(), txt_idpdt.getText(),Double.parseDouble(txt_qte.getText())));
    }else{
    cmdcltpdt.ModifClt(new CmdCltPrd(txt_idcmdclt.getText(), txt_idpdt.getText(),Double.parseDouble(txt_qte.getText())));
   
    if(type.equals("rech_pdt_cmd_clt5")){
    
    rech_pdt_cmd_clt5.AffichToutesCmdCltPdt();


    }else if(type.equals("rech_pdt_cmd_clt1")){

    rech_pdt_cmd_clt1.AffichIdPdtIdCmdClt(IdPdt, IdCmdClt);
    
    }else if(type.equals("rech_pdt_cmd_clt2")){

    rech_pdt_cmd_clt2.AffichIdCmdCltPdt(IdCmdClt);
    
    }  else if(type.equals("rech_pdt_cmd_clt3")){
                 rech_pdt_cmd_clt3.AffichQteCmdClt(IdPdt, IdCmdClt);
    }  
        
      else if(type.equals("rech_pdt_cmd_clt4")){

    rech_pdt_cmd_clt4.AffichIdPdtCmdCltPdt(IdPdt);
    
    }if(type.equals("rech_pdt_cmd_clt5")){
    
    rech_pdt_cmd_clt5.AffichToutesCmdCltPdt();


    }
        
    }  
        
        
    }//GEN-LAST:event_ajouterActionPerformed

    private void ajouter_produitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter_produitActionPerformed
        // TODO add your handling code here:
        
     txt_idpdt.setText("");
     txt_qte.setText("");
        
        
    }//GEN-LAST:event_ajouter_produitActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
        ajouterActionPerformed(null);
    }//GEN-LAST:event_modifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_pdt_cmd_clt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_pdt_cmd_clt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_pdt_cmd_clt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajout_modif_pdt_cmd_clt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajout_modif_pdt_cmd_clt(0,null,null,0.00,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton ajouter_produit;
    private javax.swing.JButton fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_idcmdclt;
    private javax.swing.JLabel lb_idpdt;
    private javax.swing.JLabel lb_qte;
    private javax.swing.JButton modifier;
    private javax.swing.JTextField txt_idcmdclt;
    private javax.swing.JTextField txt_idpdt;
    private javax.swing.JTextField txt_qte;
    // End of variables declaration//GEN-END:variables
}
