/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PFE.GUI;

import static PFE.GUI.FactFrPdt.RechIdPdtFrPdt;
import static PFE.GUI.rech_cmd_clt6.Datedebut;
import static PFE.GUI.rech_cmd_clt7.AffichToutesCmdClt;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import jxl.Workbook;
import jxl.format.Alignment;
import jxl.format.BorderLineStyle;
import jxl.format.Colour;
import jxl.format.UnderlineStyle;
import jxl.format.VerticalAlignment;
import jxl.write.Label;
import jxl.write.WritableCellFormat;
import jxl.write.WritableFont;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;

/**
 *
 * @author MOHAMED
 */
public class rech_cmd_clt4 extends javax.swing.JFrame {

      
    
     private  static  CmdClt  cmdclt=new CmdClt() ;
    private  static DefaultTableModel    mode;
    private  static Object[] row4_2 = new Object[8];
    private static   int  tr=0;
    
        
    private  String    IdCmdClt;
    private  String    IdClt;
    private  double    AvanceCmdClt;
    private  String    Prop1CmdClt;
    private  String    Prop2CmdClt;
    private  String    DateCmdClt;
    private  String    PhotoCmdClt;
    
    static String  Datedebut;
    static String  DateFin; 
    
    
    
    
    
    
    
    
    
    /**
     * Creates new form rech_cmd_clt4
     */
    public rech_cmd_clt4() {
        initComponents();
        mode=(DefaultTableModel)  tab.getModel();
      ((JTextField) txt_debut.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
       ((JTextField) txt_fin.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));

        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_debut = new javax.swing.JLabel();
        lb_fin = new javax.swing.JLabel();
        txt_debut = new com.toedter.calendar.JDateChooser();
        txt_fin = new com.toedter.calendar.JDateChooser();
        rechercher = new javax.swing.JButton();
        pdf = new javax.swing.JButton();
        excel = new javax.swing.JButton();
        fermer = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_debut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_debut.setText("Date de début : ");
        getContentPane().add(lb_debut, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 37, -1, 40));

        lb_fin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_fin.setText("Date de fin : ");
        getContentPane().add(lb_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, 40));

        txt_debut.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txt_debut, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 240, 30));

        txt_fin.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txt_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 240, 30));

        rechercher.setText("Rechercher");
        rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });
        getContentPane().add(rechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 140, 30));

        pdf.setText("PDF");
        pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfActionPerformed(evt);
            }
        });
        getContentPane().add(pdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, 70, 30));

        excel.setText("EXCEL");
        excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelActionPerformed(evt);
            }
        });
        getContentPane().add(excel, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, 70, 30));

        fermer.setText("Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });
        getContentPane().add(fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 140, 30));

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        getContentPane().add(modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 140, 30));

        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        getContentPane().add(supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 140, 30));

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identifiant CmdClt", "Date CmdClt", "Identifiant Pdt", "Designation Pdt", "Propriété1 CmdClt", "Quantité CmdClt", "Identifinat Clt", "NomClt"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 900, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PFE/GUI/background.png"))); // NOI18N
        jLabel1.setAutoscrolls(true);
        jLabel1.setMaximumSize(new java.awt.Dimension(1800, 563));
        jLabel1.setPreferredSize(new java.awt.Dimension(1500, 563));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_fermerActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed

       int i = tab.getSelectedRow();

        
                 
        
        
                if(i >= 0){
                    // remove a row from jtable

                    IdCmdClt=mode.getValueAt(i,0).toString();
                    CmdClt   cmdClt =cmdclt.RechIdCmdClt(IdCmdClt);

      new ajout_modif_cmd_clt(1, IdCmdClt,cmdClt.getIdClt(), cmdClt.getAvanceCmdClt(), cmdClt.getProp1CmdClt(), cmdClt.getProp2CmdClt(), cmdClt.getDateCmdClt(), cmdClt.getTelecharger(),"rech_cmd_clt4").setVisible(true);
            
           
                   
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                   
                     
                     
                     
                     
                }








    }//GEN-LAST:event_modifierActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed

                 int i = tab.getSelectedRow();
                if(i >= 0){
                    // remove a row from jtable

                   String IdCmdClt=mode.getValueAt(i,0).toString();
                   String IdPdt=mode.getValueAt(i,2).toString();

                    JLabel message = new JLabel("Veuillez Supprimer Cette  Commande    ");
                    JLabel title = new JLabel("Message Information !");
                    UIManager.put("OptionPane.buttonFont",new Font("Times New Roman ",0,12));
                    message.setFont(new Font("Times New Roman", 0, 14));
                    title.setFont(new Font("Times New Roman", 0, 14));

                    if( JOptionPane.showConfirmDialog(null, message,title.getText(),JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){

                       CmdCltPrd   cmdCltPdt = new CmdCltPrd();
                       cmdCltPdt.SuppCmdCltPdt(IdPdt,IdCmdClt);
                       
                        AffichToutesInfoCmdClt(Datedebut,DateFin);
                    }

                }
        
        


    }//GEN-LAST:event_supprimerActionPerformed

    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
         int  var=0;
        
    if(!((JTextField) txt_fin.getDateEditor().getUiComponent()).getText().isEmpty()){
        ((JTextField) txt_fin.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
    }
    if(((JTextField) txt_fin.getDateEditor().getUiComponent()).getText().isEmpty()){
      ((JTextField) txt_fin.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(Color.red));
      var=1;
    }
      
      
    
      if(!((JTextField) txt_debut.getDateEditor().getUiComponent()).getText().isEmpty()){
          ((JTextField)txt_debut.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
      }
   
    if(((JTextField) txt_debut.getDateEditor().getUiComponent()).getText().isEmpty()){
        ((JTextField) txt_debut.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(Color.red));
    var=1;}

    
    
    if(var==1){
        return;
    }
    
      
         
   Datedebut=((JTextField)  txt_debut.getDateEditor().getUiComponent()).getText();         
   DateFin=((JTextField)  txt_fin.getDateEditor().getUiComponent()).getText();    



















String tab_Debut[]=Datedebut.split("-");
String tab_Fin[]=DateFin.split("-");

 if(Integer.parseInt(tab_Debut[0])>Integer.parseInt(tab_Fin[0])){
   ((JTextField)  txt_debut.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(Color.red));  
   mode.setRowCount(0);
   
  return ;
   
 }else  if(Integer.parseInt(tab_Debut[0])==Integer.parseInt(tab_Fin[0])){
     
   if(Integer.parseInt(tab_Debut[1])>Integer.parseInt(tab_Fin[1])) {
       
   ((JTextField)  txt_debut.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(Color.red));  
      mode.setRowCount(0);

   return ;    
       
   }else if(Integer.parseInt(tab_Debut[1])==Integer.parseInt(tab_Fin[1])){
       
    if(Integer.parseInt(tab_Debut[2])>Integer.parseInt(tab_Fin[2])){
    ((JTextField)  txt_debut.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(Color.red));  
    mode.setRowCount(0);
     return ;        
    }
       
       
       
   }  
     
     
     
     
     
     
 }
 
     AffichToutesInfoCmdClt(Datedebut, DateFin);
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_rechercherActionPerformed

    private void pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfActionPerformed
        // TODO add your handling code here:
        
        
        
     
       
         if(mode.getRowCount()>=1){             
         try {
   Document document = new Document();
  
  
JFileChooser fileChooser = new JFileChooser();
fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
fileChooser.showOpenDialog(null);
File selectedFile = fileChooser.getSelectedFile();
String  file=selectedFile.getAbsolutePath();
if(!selectedFile.getAbsolutePath().endsWith(".pdf")){
 file=selectedFile.getAbsolutePath()+".pdf";  
}
  
  
 
  PdfWriter.getInstance(document, new FileOutputStream(file));
  document.open();
  float fntSize;
  Clt  clt = new Clt();
     
   fntSize = 10.0f;
  Image   image=Image.getInstance("C:\\Users\\HP\\Desktop\\Documents\\NetBeansProjects\\Acceuil\\src\\main\\images\\logo_4.png");
  image.setWidthPercentage(100);
  image.setAlignment(Element.ALIGN_LEFT);
  document.add(image);

  Paragraph   p3 =  new Paragraph("\n\nDate de Début  :   "+Datedebut, new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.TIMES_ROMAN, 12));
  p3.setAlignment(Element.ALIGN_LEFT);
  document.add(p3);

  
  
  Paragraph   p4 =  new Paragraph("Date de Fin :    "+DateFin, new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.TIMES_ROMAN, 12));
  p4.setAlignment(Element.ALIGN_LEFT);
  document.add(p4);
  
    document.add( Chunk.NEWLINE );

  Paragraph   p5 =  new Paragraph("   La Liste Des Commandes  Effectué Entre Les Deux Dates     ", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.TIMES_ROMAN, 14));
  p5.setAlignment(Element.ALIGN_CENTER);
  document.add(p5);
  PdfPTable table =  new PdfPTable(8);
  table.setWidthPercentage(105);
  table.setHorizontalAlignment(Element.ALIGN_BOTTOM);
  PdfPCell cel1;
  table.setWidths(new float[] { 68,68,68,68,68,68,68,68 });
  com.itextpdf.text.Font font = FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.BOLD, BaseColor.WHITE);
  com.itextpdf.text.Font font2 = FontFactory.getFont(FontFactory.TIMES_ROMAN, fntSize);

       
  
  
  
  cel1 = new PdfPCell(new Phrase("Identifiant CmdClt ", font));
            cel1.setFixedHeight(20);
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);

            cel1 = new PdfPCell(new Phrase(" Date CmdClt ", font));
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);



            cel1 = new PdfPCell(new Phrase(" Identifiant Pdt  ", font));
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
            
           
      cel1 = new PdfPCell(new Phrase(" Designation Pdt ", font));
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
            
      cel1 = new PdfPCell(new Phrase(" Propriété 1 CmdClt  ", font));
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
            
              cel1 = new PdfPCell(new Phrase(" Quantité CmdClt ", font));
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
            
              cel1 = new PdfPCell(new Phrase(" Identifiant Clt ", font));
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
            
            
             cel1 = new PdfPCell(new Phrase(" Nom Clt ", font));
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
            
         
            
            
            
            
            
            
            
            
            
            
            
            
            
              
              
        ArrayList< String>  tab =cmdclt.RechToutesInfoCmdClt(Datedebut,DateFin);
    
    
    
    
    
    
  
    for(String  str :  tab){
        
            
            cel1 = new PdfPCell(new Phrase(str, font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);

     
      
    
            
            
          
    }
   
             
              
                   
              
              
              
              
              
              
              
                 
            
         
                   
   JOptionPane.showMessageDialog(null, "PDF a éte enregistrer  ","Message Information",JOptionPane.INFORMATION_MESSAGE);
        
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            

   
   
   
   
    document.add( new Phrase("\n") );
    document.add(table);
    document.add( Chunk.NEWLINE );

 SimpleDateFormat simpleFormatter = new SimpleDateFormat("         dd/MM/yyyy  hh:mm:ss");
 String date=simpleFormatter.format(new Date());
 Paragraph  p2 = new Paragraph(date,FontFactory.getFont(FontFactory.TIMES_ROMAN,12));
 p2.setAlignment(Element.ALIGN_RIGHT);
 document.add(p2);

           
                    
  
  
  
  
  
  
  
    document.close();

  
  
} catch (Exception e) {
}        
                 
                 
                 
     }               
                 
                 
                 
                 
                   
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
              
                   
                   
        
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            

   
   
        
                 
                 
                 
                   
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
                 
                 
                 
                 
                   
        
        
        











   
        
        
        
        
        
        
        
        
        
        
        
        
           
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_pdfActionPerformed

    private void excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelActionPerformed
        // TODO add your handling code here:
        
        
    
        

         
                 if(mode.getRowCount()>=1){
    try {

File selectedFile=null;       
JFileChooser fileChooser = new JFileChooser();
fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
fileChooser.showOpenDialog(null);
selectedFile = fileChooser.getSelectedFile();
if(selectedFile!=null){
    

 String  file=selectedFile.getAbsolutePath();
if(!selectedFile.getAbsolutePath().endsWith(".xls")){
 file=selectedFile.getAbsolutePath()+".xls";  
}
  
    WritableWorkbook workbook = Workbook.createWorkbook(new File(file));
    WritableSheet writablesheet1 = workbook.createSheet("Sheet1", 0);
    WritableFont times10pt = new WritableFont(WritableFont.TIMES, 12,WritableFont.BOLD);
    WritableFont times12pt = new WritableFont(WritableFont.TIMES, 11);

    
    
    int  rows =6;
   // Define the cell format
   WritableCellFormat  times = new WritableCellFormat(times10pt);
   WritableCellFormat  times2 = new WritableCellFormat(times12pt);
   times.setBorder(jxl.format.Border.ALL, BorderLineStyle.THIN, Colour.BLACK);
   times2.setBorder(jxl.format.Border.ALL, BorderLineStyle.THIN, Colour.BLACK);
   times.setBackground(Colour.WHITE);
   times.setAlignment(Alignment.CENTRE);
   times.setVerticalAlignment(VerticalAlignment.CENTRE);
   times2.setWrap(true);
   
   times2.setAlignment(Alignment.CENTRE);
   times2.setVerticalAlignment(VerticalAlignment.CENTRE);
   WritableCellFormat cellFormat = new WritableCellFormat(times);
   cellFormat.setBackground(Colour.YELLOW);
   cellFormat.setBorder(jxl.format.Border.ALL, BorderLineStyle.THIN);
   // Lets automatically wrap the cells
   // Create create a bold font with unterlines
   WritableFont times10ptBoldUnderline = new WritableFont(
   WritableFont.TIMES, 12, WritableFont.BOLD, false,
   UnderlineStyle.SINGLE);
   // Lets automatically wrap the cells

  Label label;
   Clt clt = new Clt();
   label = new Label(2, 0, "           Stock  Super Marché  ", new WritableCellFormat(new WritableFont(
   WritableFont.TIMES, 16, WritableFont.BOLD)));
   writablesheet1.addCell(label);
  
    label = new Label(0, 1, "Date De Début  :   "+Datedebut, new WritableCellFormat(new WritableFont(
   WritableFont.TIMES, 12, WritableFont.BOLD)));
   writablesheet1.addCell(label);
  
   label = new Label(0, 2, "Date De Fin  :     "+DateFin, new WritableCellFormat(new WritableFont(
   WritableFont.TIMES, 12, WritableFont.BOLD)));
   writablesheet1.addCell(label);
  








   label = new Label(2, 3, "La Liste Des  Commandes  Effectué Entre Les Deux Dates  ", new WritableCellFormat(new WritableFont(
   WritableFont.TIMES, 14, WritableFont.BOLD)));
   writablesheet1.addCell(label);
    
   


   
   
   
   
   writablesheet1.setRowView(5, 26*24);
   
   
   writablesheet1.setColumnView(1,35);
   Label label1 = new Label(1,5,"Identifiant CmdClt ",cellFormat);
   writablesheet1.setColumnView(2,35);
   Label label10 = new Label(2,5,"Date CmdClt",cellFormat);  
   writablesheet1.setColumnView(3, 35);
   Label label2 = new Label(3,5,"Identifiant Pdt",cellFormat);
   writablesheet1.setColumnView(4,35);
   Label label3 = new Label(4,5,"Designation Pdt ",cellFormat);
   writablesheet1.setColumnView(5,35);
   Label label4 = new Label(5,5,"Propriété 1 CmdClt",cellFormat);  
   writablesheet1.setColumnView(6, 35);
   Label label5 = new Label(6,5,"Quantité CmdClt",cellFormat);
   writablesheet1.setColumnView(7,35);
   Label label6 = new Label(7,5,"Identifiant Clt ",cellFormat);
   writablesheet1.setColumnView(8,35);
   Label label7 = new Label(8,5,"Nom C1l",cellFormat);  
  
   
     
   
   
     
   
   
    
   
   
  
    writablesheet1.addCell(label1);
    writablesheet1.addCell(label10);
    writablesheet1.addCell(label2);

    
    writablesheet1.addCell(label3);
    writablesheet1.addCell(label4);
    writablesheet1.addCell(label5);

    
    writablesheet1.addCell(label6);
    writablesheet1.addCell(label7);

    
    
    
    
    
    


    writablesheet1.setColumnView(0,30);
    writablesheet1.setColumnView(1,30);
    writablesheet1.setColumnView(2,30);
    writablesheet1.setColumnView(3,30);
    writablesheet1.setColumnView(4,30);
    writablesheet1.setColumnView(5,30);
    writablesheet1.setColumnView(6,30);
    writablesheet1.setColumnView(7,30);
        
 
         ArrayList <String> table=cmdclt.RechToutesInfoCmdClt(Datedebut, DateFin);      
   
                 
    int i=1;     
           

   for(String  str : table){
  
      if(i==9){
        i=1;
      
       rows++;
          
      }
       
       
     writablesheet1.addCell(new Label(i,rows,str,times2));
     
     i++;
 
   
   
   }
       
        
                
              
          
    
   
    
         JOptionPane.showMessageDialog(null, "Excel a éte enregistrer  ","Message Information",JOptionPane.INFORMATION_MESSAGE);

   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
     
    workbook.write();
    workbook.close();
    
}}  
    
catch (WriteException e) {
    JOptionPane.showMessageDialog(null, e);}
catch (IOException ex) {}        
                         
                 
                 
                 
           }      
                 
                 
                 
       
        
        
        
        
             
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_excelActionPerformed

    
    
    public static void AffichToutesInfoCmdClt(String DateDebut ,String  DateFin){
        
        
              
              
           
 if(tr==0){  
      
         ArrayList <String> tab=cmdclt.RechToutesInfoCmdClt(DateDebut, DateFin);      

      if(tab!=null){
  
          
 int i=0;   
 
for(String    str :tab){  

  if(i==8){
   mode.addRow(row4_2); 
   i=0;
  }  
    
    
 row4_2[i]=str;
 i++;
    
 


}

   mode.addRow(row4_2); 



      }else{
          
    mode.setRowCount(0);
    
    
     JLabel message = new JLabel(" Commandes inexistantes  ");
     JLabel title = new JLabel("Message Information !");
     UIManager.put("OptionPane.okButtonText", " Oui");
     UIManager.put("OptionPane.buttonFont", new Font("Times New Roman ",0,12)); 
     JOptionPane.showMessageDialog(null, message,title.getText(),JOptionPane.INFORMATION_MESSAGE);
          
      }
      tr=1;    
     return ;
           
 

            
            
            
        }else if(tr==1){
        tr=0;
        mode.setRowCount(0);
        AffichToutesInfoCmdClt(DateDebut, DateFin);
  
 }      
     
        
        
        
          
               
 
       
        
    }
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rech_cmd_clt4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rech_cmd_clt4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rech_cmd_clt4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rech_cmd_clt4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rech_cmd_clt4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton excel;
    private javax.swing.JButton fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_debut;
    private javax.swing.JLabel lb_fin;
    private javax.swing.JButton modifier;
    private javax.swing.JButton pdf;
    private javax.swing.JButton rechercher;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable tab;
    private com.toedter.calendar.JDateChooser txt_debut;
    private com.toedter.calendar.JDateChooser txt_fin;
    // End of variables declaration//GEN-END:variables
}
