/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PFE.GUI;

import static PFE.GUI.rech_pdt_cmd_clt5.AffichToutesCmdCltPdt;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MOHAMED
 */
public class rech_pdt_cmd_clt1 extends javax.swing.JFrame {

    /**
     * Creates new form rech_pdt_cmd_clt1
     */
    
    private  static DefaultTableModel    mode;
    private  static Object[] row4_2 = new Object[3];
    private static   int  tr=0;
    private  static CmdCltPrd   cmdcltpdt =  new CmdCltPrd();
    private  String    IdCmdClt;
    private  String    IdPdt;
    private  double    QteCmdClt;
    
    
    public rech_pdt_cmd_clt1() {
        initComponents();
        
         txt_idpdt.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
         txt_idcmdclt.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
       
          mode=(DefaultTableModel)  tab.getModel();

        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_idcmdclt = new javax.swing.JLabel();
        lb_idpdt = new javax.swing.JLabel();
        txt_idcmdclt = new javax.swing.JTextField();
        txt_idpdt = new javax.swing.JTextField();
        rechercher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        fermer = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_idcmdclt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_idcmdclt.setText("Identifiant de la commande d'un client : ");
        getContentPane().add(lb_idcmdclt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        lb_idpdt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_idpdt.setText("Identifient du produit : ");
        getContentPane().add(lb_idpdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));
        getContentPane().add(txt_idcmdclt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 310, 30));
        getContentPane().add(txt_idpdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 310, 30));

        rechercher.setText("Rechercher");
        rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });
        getContentPane().add(rechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 140, 30));

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identifiant de la commande", "Identifiant du pdt", "Quantité Commondée"
            }
        ));
        jScrollPane1.setViewportView(tab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 200, 790, 190));

        fermer.setText("Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });
        getContentPane().add(fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 120, 30));

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        getContentPane().add(modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 120, 30));

        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        getContentPane().add(supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PFE/GUI/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 881, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_fermerActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed

 int i = tab.getSelectedRow();

        
                 
        
        
                if(i >= 0){
                    // remove a row from jtable

                    IdCmdClt=mode.getValueAt(i,0).toString();
                    IdPdt=mode.getValueAt(i,1).toString();
                    QteCmdClt=Double.parseDouble(mode.getValueAt(i,2).toString());
                   

             new ajout_modif_pdt_cmd_clt(1, IdCmdClt,IdPdt, QteCmdClt,"rech_pdt_cmd_clt1").setVisible(true);
            
           
                }
               



    }//GEN-LAST:event_modifierActionPerformed

    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherActionPerformed
        // TODO add your handling code here:
        
          int  var=0;
    
        if(txt_idcmdclt.getText().isEmpty()){
          txt_idcmdclt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));}
      
        if(txt_idpdt.getText().isEmpty()){
          txt_idpdt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));}

        
        
    if(txt_idcmdclt.getText().isEmpty()){
       var=1;
       txt_idcmdclt.setBorder(BorderFactory.createLineBorder(Color.red));}
     if(txt_idpdt.getText().isEmpty()){
       var=1;
       txt_idpdt.setBorder(BorderFactory.createLineBorder(Color.red));} 
        
    if(var==1){
        return;
    }    
        
       
       
      AffichIdPdtIdCmdClt (txt_idpdt.getText(),txt_idcmdclt.getText()) ;
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_rechercherActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
        
           int i = tab.getSelectedRow();
                if(i >= 0){
                    // remove a row from jtable

                   String IdCmdClt=mode.getValueAt(i,0).toString();
                   String IdPdt=mode.getValueAt(i,1).toString();

                    JLabel message = new JLabel("Veuillez Supprimer Cette  Commande Clt    ");
                    JLabel title = new JLabel("Message Information !");
                    UIManager.put("OptionPane.buttonFont",new Font("Times New Roman ",0,12));
                    message.setFont(new Font("Times New Roman", 0, 14));
                    title.setFont(new Font("Times New Roman", 0, 14));

                    if( JOptionPane.showConfirmDialog(null, message,title.getText(),JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){

                        cmdcltpdt.SuppCmdCltPdt(IdPdt,IdCmdClt);
                         mode.setRowCount(0);

                    }

                }
        
    }//GEN-LAST:event_supprimerActionPerformed

    
    
    
    
    
    
    
    public static   void AffichIdPdtIdCmdClt(String IdPdt ,String IdCmdClt){
        
        
        
          
         
        
    if(tr==0){  
      
      if((cmdcltpdt=cmdcltpdt.RechIdPdtIdCmdClt(IdPdt, IdCmdClt))!=null){
  
 

        
     row4_2[0]=cmdcltpdt.getIdCmdClt();
     row4_2[1]=cmdcltpdt.getIdPdt();
     row4_2[2]=cmdcltpdt.getQteCmdClt();
    
     
      mode.addRow(row4_2);   
        
        
        
   
                  
                  
          
          
          
          
          
          
   

            
     }else{
          
        mode.setRowCount(0);
    
    
     JLabel message = new JLabel("objet inéxistant");
     JLabel title = new JLabel("Message Information !");
     UIManager.put("OptionPane.okButtonText", " Oui");
     UIManager.put("OptionPane.buttonFont", new Font("Times New Roman ",0,12)); 
     JOptionPane.showMessageDialog(null, message,title.getText(),JOptionPane.INFORMATION_MESSAGE);
          
      }
      tr=1;    
      return ;
           
 

            
            
            
        }else if(tr==1){
        tr=0;
        mode.setRowCount(0);
        AffichIdPdtIdCmdClt(IdPdt, IdCmdClt);
       
        
        
        
        
        
        
    } 
        
        
        
        
        
        
        
        
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rech_pdt_cmd_clt1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rech_pdt_cmd_clt1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rech_pdt_cmd_clt1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rech_pdt_cmd_clt1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rech_pdt_cmd_clt1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_idcmdclt;
    private javax.swing.JLabel lb_idpdt;
    private javax.swing.JButton modifier;
    private javax.swing.JButton rechercher;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txt_idcmdclt;
    private javax.swing.JTextField txt_idpdt;
    // End of variables declaration//GEN-END:variables
}
