/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PFE.GUI;

import static PFE.GUI.rech_cmd_clt6.Datedebut;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import jxl.Workbook;
import jxl.format.Alignment;
import jxl.format.BorderLineStyle;
import jxl.format.Colour;
import jxl.format.UnderlineStyle;
import jxl.format.VerticalAlignment;
import jxl.write.Label;
import jxl.write.WritableCellFormat;
import jxl.write.WritableFont;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;

/**
 *
 * @author MOHAMED
 */
public class rech_cmd_clt8 extends javax.swing.JFrame {

    /**
     * Creates new form rech_cmd_clt8
     */
    
    private  static  CmdClt  cmdclt=new CmdClt() ;
    private  static DefaultTableModel    mode;
    private  static Object[] row4_2 = new Object[3];
    private static   int  tr=0;
    
        
    private  String    IdCmdClt;
    private  String    IdClt;
    private  double    AvanceCmdClt;
    private  String    Prop1CmdClt;
    private  String    Prop2CmdClt;
    private  String    DateCmdClt;
    private  String    PhotoCmdClt;
    static String  Datedebut;
    static String  DateFin;
     
    public rech_cmd_clt8() {
        initComponents();
            
        mode=(DefaultTableModel)  tab.getModel();
      ((JTextField) txt_debut.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
       ((JTextField) txt_fin.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));

      
    
    
    

 
 
 
 
 
 
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_debut = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txt_fin = new com.toedter.calendar.JDateChooser();
        Rechercher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        pdf = new javax.swing.JButton();
        excel = new javax.swing.JButton();
        Fermer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Date de début : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        txt_debut.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txt_debut, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 250, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Date de fin : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        txt_fin.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txt_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 250, 30));

        Rechercher.setText("Rechercher");
        Rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherActionPerformed(evt);
            }
        });
        getContentPane().add(Rechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 130, 30));

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Designation du Produit", "Propriété 1 ", "Quantité Commandée"
            }
        ));
        jScrollPane1.setViewportView(tab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 160, 870, 230));

        pdf.setText("PDF");
        pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfActionPerformed(evt);
            }
        });
        getContentPane().add(pdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 180, 70, 30));

        excel.setText("EXCEL");
        excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelActionPerformed(evt);
            }
        });
        getContentPane().add(excel, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, 70, 30));

        Fermer.setText("Fermer");
        Fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FermerActionPerformed(evt);
            }
        });
        getContentPane().add(Fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 413, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PFE/GUI/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FermerActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_FermerActionPerformed

    private void RechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherActionPerformed
        // TODO add your handling code here:
        
          
         int  var=0;
        
    if(!((JTextField) txt_fin.getDateEditor().getUiComponent()).getText().isEmpty()){
        ((JTextField) txt_fin.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
    }
    if(((JTextField) txt_fin.getDateEditor().getUiComponent()).getText().isEmpty()){
      ((JTextField) txt_fin.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(Color.red));
      var=1;
    }
      
      
    
      if(!((JTextField) txt_debut.getDateEditor().getUiComponent()).getText().isEmpty()){
          ((JTextField)txt_debut.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
      }
   
    if(((JTextField) txt_debut.getDateEditor().getUiComponent()).getText().isEmpty()){
        ((JTextField) txt_debut.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(Color.red));
    var=1;}

    
    
    if(var==1){
        return;
    }
    
      
         
   Datedebut=((JTextField)  txt_debut.getDateEditor().getUiComponent()).getText();         
   DateFin=((JTextField)  txt_fin.getDateEditor().getUiComponent()).getText();    



















String tab_Debut[]=Datedebut.split("-");
String tab_Fin[]=DateFin.split("-");

 if(Integer.parseInt(tab_Debut[0])>Integer.parseInt(tab_Fin[0])){
   ((JTextField)  txt_debut.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(Color.red));  
   mode.setRowCount(0);
   
  return ;
   
 }else  if(Integer.parseInt(tab_Debut[0])==Integer.parseInt(tab_Fin[0])){
     
   if(Integer.parseInt(tab_Debut[1])>Integer.parseInt(tab_Fin[1])) {
       
   ((JTextField)  txt_debut.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(Color.red));  
      mode.setRowCount(0);

   return ;    
       
   }else if(Integer.parseInt(tab_Debut[1])==Integer.parseInt(tab_Fin[1])){
       
    if(Integer.parseInt(tab_Debut[2])>Integer.parseInt(tab_Fin[2])){
    ((JTextField)  txt_debut.getDateEditor().getUiComponent()).setBorder(BorderFactory.createLineBorder(Color.red));  
    mode.setRowCount(0);
     return ;        
    }
       
       
       
   }  
     
     
     
     
     
     
 }
 
        AffichCmdCltAPasser(Datedebut, DateFin);
        
        
        
        
        
    }//GEN-LAST:event_RechercherActionPerformed

    private void pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfActionPerformed
        // TODO add your handling code here:
        
       
         if(mode.getRowCount()>=1){             
         try {
   Document document = new Document();
  
  
JFileChooser fileChooser = new JFileChooser();
fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
fileChooser.showOpenDialog(null);
File selectedFile = fileChooser.getSelectedFile();
String  file=selectedFile.getAbsolutePath();
if(!selectedFile.getAbsolutePath().endsWith(".pdf")){
 file=selectedFile.getAbsolutePath()+".pdf";  
}
  
  
 
  PdfWriter.getInstance(document, new FileOutputStream(file));
  document.open();
  float fntSize;
  Clt  clt = new Clt();
     
   fntSize = 10.0f;
  Image   image=Image.getInstance("C:\\Users\\HP\\Desktop\\Documents\\NetBeansProjects\\Acceuil\\src\\main\\images\\logo_4.png");
  image.setWidthPercentage(100);
  image.setAlignment(Element.ALIGN_LEFT);
  document.add(image);

  Paragraph   p3 =  new Paragraph("\n\nDate de Début  :   "+Datedebut, new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.TIMES_ROMAN, 12));
  p3.setAlignment(Element.ALIGN_LEFT);
  document.add(p3);

  
  
  Paragraph   p4 =  new Paragraph("Date de Fin :    "+DateFin, new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.TIMES_ROMAN, 12));
  p4.setAlignment(Element.ALIGN_LEFT);
  document.add(p4);
  
    document.add( Chunk.NEWLINE );

  Paragraph   p5 =  new Paragraph("   La Liste Des Commandes  Effectué Entre Les Deux Dates     ", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.TIMES_ROMAN, 14));
  p5.setAlignment(Element.ALIGN_CENTER);
  document.add(p5);
  PdfPTable table =  new PdfPTable(3);
  table.setWidthPercentage(105);
  table.setHorizontalAlignment(Element.ALIGN_BOTTOM);
  PdfPCell cel1;
  table.setWidths(new float[] { 191,191,191 });
  com.itextpdf.text.Font font = FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.BOLD, BaseColor.WHITE);
  com.itextpdf.text.Font font2 = FontFactory.getFont(FontFactory.TIMES_ROMAN, fntSize);

       
  
  
  
  cel1 = new PdfPCell(new Phrase(" Desgination Du Produit ", font));
            cel1.setFixedHeight(20);
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);

            cel1 = new PdfPCell(new Phrase(" Propriété 1 ", font));
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);



            cel1 = new PdfPCell(new Phrase(" Quantité Commandée ", font));
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
            
           
    
            
            
         
            
            
            
            
            
            
            
            
            
            
            
            
            
              
              
        ArrayList< String>  tab =cmdclt.RechDesigPdtQteCmdClt(Datedebut,DateFin);
    
    
    
    
    
    
  
    for(String  str :  tab){
        
            
            cel1 = new PdfPCell(new Phrase(str, font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);

     
      
    
            
            
          
    }
   
             
              
                   
              
              
              
              
              
              
              
                 
            
         
                   
   JOptionPane.showMessageDialog(null, "PDF a éte enregistrer  ","Message Information",JOptionPane.INFORMATION_MESSAGE);
        
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            

   
   
   
   
    document.add( new Phrase("\n") );
    document.add(table);
    document.add( Chunk.NEWLINE );

 SimpleDateFormat simpleFormatter = new SimpleDateFormat("         dd/MM/yyyy  hh:mm:ss");
 String date=simpleFormatter.format(new Date());
 Paragraph  p2 = new Paragraph(date,FontFactory.getFont(FontFactory.TIMES_ROMAN,12));
 p2.setAlignment(Element.ALIGN_RIGHT);
 document.add(p2);

           
                    
  
  
  
  
  
  
  
    document.close();

  
  
} catch (Exception e) {
}        
                 
                 
                 
     }               
                 
                 
                 
                 
                   
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
              
                   
                   
        
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            

   
   
        
                 
                 
                 
                   
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
                 
                 
                 
                 
                   
        
        
        











   
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_pdfActionPerformed

    private void excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelActionPerformed
        // TODO add your handling code here:
        
           
        
        
        

         
                 if(mode.getRowCount()>=1){
    try {

File selectedFile=null;       
JFileChooser fileChooser = new JFileChooser();
fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
fileChooser.showOpenDialog(null);
selectedFile = fileChooser.getSelectedFile();
if(selectedFile!=null){
    

 String  file=selectedFile.getAbsolutePath();
if(!selectedFile.getAbsolutePath().endsWith(".xls")){
 file=selectedFile.getAbsolutePath()+".xls";  
}
  
    WritableWorkbook workbook = Workbook.createWorkbook(new File(file));
    WritableSheet writablesheet1 = workbook.createSheet("Sheet1", 0);
    WritableFont times10pt = new WritableFont(WritableFont.TIMES, 12,WritableFont.BOLD);
    WritableFont times12pt = new WritableFont(WritableFont.TIMES, 11);

    
    
    int  rows =6;
   // Define the cell format
   WritableCellFormat  times = new WritableCellFormat(times10pt);
   WritableCellFormat  times2 = new WritableCellFormat(times12pt);
   times.setBorder(jxl.format.Border.ALL, BorderLineStyle.THIN, Colour.BLACK);
   times2.setBorder(jxl.format.Border.ALL, BorderLineStyle.THIN, Colour.BLACK);
   times.setBackground(Colour.WHITE);
   times.setAlignment(Alignment.CENTRE);
   times.setVerticalAlignment(VerticalAlignment.CENTRE);
   times2.setWrap(true);
   
   times2.setAlignment(Alignment.CENTRE);
   times2.setVerticalAlignment(VerticalAlignment.CENTRE);
   WritableCellFormat cellFormat = new WritableCellFormat(times);
   cellFormat.setBackground(Colour.YELLOW);
   cellFormat.setBorder(jxl.format.Border.ALL, BorderLineStyle.THIN);
   // Lets automatically wrap the cells
   // Create create a bold font with unterlines
   WritableFont times10ptBoldUnderline = new WritableFont(
   WritableFont.TIMES, 12, WritableFont.BOLD, false,
   UnderlineStyle.SINGLE);
   // Lets automatically wrap the cells

  Label label;
   Clt clt = new Clt();
   label = new Label(2, 0, "           Stock  Super Marché  ", new WritableCellFormat(new WritableFont(
   WritableFont.TIMES, 16, WritableFont.BOLD)));
   writablesheet1.addCell(label);
  
    label = new Label(0, 1, "Date De Début  :   "+Datedebut, new WritableCellFormat(new WritableFont(
   WritableFont.TIMES, 12, WritableFont.BOLD)));
   writablesheet1.addCell(label);
  
   label = new Label(0, 2, "Date De Fin  :     "+DateFin, new WritableCellFormat(new WritableFont(
   WritableFont.TIMES, 12, WritableFont.BOLD)));
   writablesheet1.addCell(label);
  








   label = new Label(2, 3, "La Liste Des  Commandes  Effectué Entre Les Deux Dates  ", new WritableCellFormat(new WritableFont(
   WritableFont.TIMES, 14, WritableFont.BOLD)));
   writablesheet1.addCell(label);
    
   


   
   
   
   
   writablesheet1.setRowView(5, 26*24);
   
   
   writablesheet1.setColumnView(1,35);
   Label label1 = new Label(1,5,"Designation Du Produit ",cellFormat);
   writablesheet1.setColumnView(2,35);
   Label label10 = new Label(2,5,"Propriété 1",cellFormat);  
   writablesheet1.setColumnView(3, 35);
   Label label2 = new Label(3,5,"Quantité Commandée",cellFormat);

     
   
   
     
   
   
    
   
   
  
    writablesheet1.addCell(label1);
    writablesheet1.addCell(label10);
    writablesheet1.addCell(label2);

    
    
    
    
    
    


    writablesheet1.setColumnView(0,30);
    writablesheet1.setColumnView(1,30);
    writablesheet1.setColumnView(2,30);
    
    
 
         ArrayList <String> table=cmdclt.RechDesigPdtQteCmdClt(Datedebut, DateFin);      
   
                 
    int i=1;     
           

   for(String  str : table){
  
      if(i==4){
        i=1;
      
       rows++;
          
      }
       
       
     writablesheet1.addCell(new Label(i,rows,str,times2));
     
     i++;
 
   
   
   }
       
        
                
              
          
    
   
    
         JOptionPane.showMessageDialog(null, "Excel a éte enregistrer  ","Message Information",JOptionPane.INFORMATION_MESSAGE);

   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
     
    workbook.write();
    workbook.close();
    
}}  
    
catch (WriteException e) {
    JOptionPane.showMessageDialog(null, e);}
catch (IOException ex) {}        
                         
                 
                 
                 
           }      
                 
                 
                 
       
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_excelActionPerformed

    
               public  void AffichCmdCltAPasser (String DateDebut,String  DateFin) {
     

               
              
           
 if(tr==0){  
      
         ArrayList <String> tab=cmdclt.RechCmdCltAPasser(DateDebut, DateFin);      

      if(tab!=null){
  
          
 int i=0;   
 
for(String    str :tab){  

  if(i==3){
   mode.addRow(row4_2); 
   i=0;
  }  
    
    
 row4_2[i]=str;
 i++;
    
 


}

   mode.addRow(row4_2); 



      }else{
          
    mode.setRowCount(0);
    
    
     JLabel message = new JLabel(" Commandes inexistantes  ");
     JLabel title = new JLabel("Message Information !");
     UIManager.put("OptionPane.okButtonText", " Oui");
     UIManager.put("OptionPane.buttonFont", new Font("Times New Roman ",0,12)); 
     JOptionPane.showMessageDialog(null, message,title.getText(),JOptionPane.INFORMATION_MESSAGE);
          
      }
      tr=1;    
     return ;
           
 

            
            
            
        }else if(tr==1){
        tr=0;
        mode.setRowCount(0);
        AffichCmdCltAPasser(DateDebut, DateFin);
  
 }      
     
        
        
        
          
               

            
            
            
        }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rech_cmd_clt8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rech_cmd_clt8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rech_cmd_clt8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rech_cmd_clt8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rech_cmd_clt8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fermer;
    private javax.swing.JButton Rechercher;
    private javax.swing.JButton excel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pdf;
    private javax.swing.JTable tab;
    private com.toedter.calendar.JDateChooser txt_debut;
    private com.toedter.calendar.JDateChooser txt_fin;
    // End of variables declaration//GEN-END:variables
}
