/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PFE.GUI;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MOHAMED
 */
public class rech_pdt_in_facture extends javax.swing.JFrame {
   
    /**
     * Creates new form rech_pdt_in_facture
     */
    private static DefaultTableModel   mode ;
    private static FactFrPdt  factfrpdt = new FactFrPdt(); 
    private static Object[] row = new Object[4];

    public rech_pdt_in_facture() {
        initComponents();
       mode=(DefaultTableModel)    tab.getModel();
txt_lb_idfact.setBorder(BorderFactory.createLineBorder(new Color(45,18,232)));
txt_lb_idpdt.setBorder(BorderFactory.createLineBorder(new Color(45,18,232)));

    }

    public static void AffichIdPdtIdFactFr (String IdFactFr,String IdPdt) {
      
      
      
      if(factfrpdt.RechIdPdtIdFactFr(IdFactFr, IdPdt)!=null){
          
          
   FactFrPdt  factFrPdt =  factfrpdt.RechIdPdtIdFactFr(IdFactFr, IdPdt);
   
   
   row[0]=factFrPdt.getIdFactFr();
   row[1]=factFrPdt.getIdPdt();
   row[2]=factFrPdt.getQteAchatPdt();
   row[3]=factFrPdt.getPrxAchatPdt();
 
   mode.addRow(row);
          
          
  if(mode.getRowCount()>=2){
  
       mode.removeRow(0);
   }          
          
          
          
            
     }else{
          
    mode.setRowCount(0);
    
    
     JLabel message = new JLabel("Objet Inexistant");
     JLabel title = new JLabel("Message Information !");
     UIManager.put("OptionPane.okButtonText", " Oui");
     UIManager.put("OptionPane.buttonFont", new Font("Times New Roman ",0,12)); 
     JOptionPane.showMessageDialog(null, message,title.getText(),JOptionPane.INFORMATION_MESSAGE);
          
      }
      
 

            
            
            
        }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
   
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_lb_idfact = new javax.swing.JTextField();
        txt_lb_idpdt = new javax.swing.JTextField();
        Rechercher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        Fermer = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Identifiant de la facture : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 37, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Identifiant du produit   : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 87, 160, 30));
        getContentPane().add(txt_lb_idfact, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 310, 30));
        getContentPane().add(txt_lb_idpdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 310, 30));

        Rechercher.setText("Rechercher");
        Rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherActionPerformed(evt);
            }
        });
        getContentPane().add(Rechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 133, -1, 30));

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identifiant de la Facture", "Identifiant Produit", "Quantité", "Prix d'achat"
            }
        ));
        jScrollPane1.setViewportView(tab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 910, 220));

        Fermer.setText("Fermer");
        Fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FermerActionPerformed(evt);
            }
        });
        getContentPane().add(Fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 100, 30));

        Modifier.setText("Modifier");
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });
        getContentPane().add(Modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 100, 30));

        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(Supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PFE/GUI/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherActionPerformed
        // TODO add your handling code here:
        
        
 if(txt_lb_idpdt.getText().isEmpty() ){txt_lb_idpdt.setBorder(BorderFactory.createLineBorder(Color.RED));} 
 if(txt_lb_idfact.getText().isEmpty() ){txt_lb_idfact.setBorder(BorderFactory.createLineBorder(Color.RED));}      
                     
                     
                     
if(!txt_lb_idpdt.getText().isEmpty() && !txt_lb_idfact.getText().isEmpty()){
 txt_lb_idpdt.setBorder(BorderFactory.createLineBorder(new Color(45,18,232)));
txt_lb_idfact.setBorder(BorderFactory.createLineBorder(new Color(45,18,232)));
AffichIdPdtIdFactFr(txt_lb_idfact.getText(), txt_lb_idpdt.getText());                 }
   
    
    
        
    }//GEN-LAST:event_RechercherActionPerformed

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed




   // i = the index of the selected row
                int i = tab.getSelectedRow();
                if(i >= 0){
                    // remove a row from jtable                   
                 new  ajout_modif_produit_in_facture(1, mode.getValueAt(i,0).toString(), mode.getValueAt(i,1).toString(),(double) mode.getValueAt(i,2), (double)mode.getValueAt(i,3),"rech_pdt_in_facture").setVisible(true);}








    }//GEN-LAST:event_ModifierActionPerformed

    private void FermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FermerActionPerformed
        this.dispose();
    }//GEN-LAST:event_FermerActionPerformed

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        // TODO add your handling code here:
         int i = tab.getSelectedRow();
                if(i >= 0){
                    // remove a row from jtable


                    JLabel message = new JLabel("Veuillez Supprimer Cette Facture  ?  ");
                    JLabel title = new JLabel("Message Information !");
                    UIManager.put("OptionPane.buttonFont",new Font("Times New Roman ",0,12));
                    message.setFont(new Font("Times New Roman", 0, 14));
                    title.setFont(new Font("Times New Roman", 0, 14));

                    if( JOptionPane.showConfirmDialog(null, message,title.getText(),JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){

                       factfrpdt.SuppFactFrPdt(mode.getValueAt(i, 0).toString(),mode.getValueAt(i, 1).toString());
                       mode.removeRow(i);

                    }}
    }//GEN-LAST:event_SupprimerActionPerformed

                
                
                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rech_pdt_in_facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rech_pdt_in_facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rech_pdt_in_facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rech_pdt_in_facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rech_pdt_in_facture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fermer;
    private javax.swing.JButton Modifier;
    private javax.swing.JButton Rechercher;
    private javax.swing.JButton Supprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txt_lb_idfact;
    private javax.swing.JTextField txt_lb_idpdt;
    // End of variables declaration//GEN-END:variables
}
