/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PFE.GUI;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MOHAMMED
 */
public class rech_cmd_clt1 extends javax.swing.JFrame {

    /**
     * Creates new form rech_cmd_clt1
     */
    
    private  static  CmdClt  cmdclt=new CmdClt() ;
    private  static DefaultTableModel    mode;
    private  static Object[] row4_2 = new Object[7];
    private static   int  tr=0;
    
        
    private  String    IdCmdClt;
    private  String    IdClt;
    private  double    AvanceCmdClt;
    private  String    Prop1CmdClt;
    private  String    Prop2CmdClt;
    private  String    DateCmdClt;
    private  String    PhotoCmdClt;
    
    
    public rech_cmd_clt1() {
        initComponents();
       mode=(DefaultTableModel)  tab.getModel();
       txt_idcmdclt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
   tab.addMouseListener(new MouseAdapter() {
    
    
    
    
    
    
 @Override
 public void mousePressed(MouseEvent e) {

      
      
      
 
      try {
          
          
        int row = tab.getSelectedRow();
        int col = tab.getSelectedColumn();
        
             
        
        Runtime     rt=Runtime.getRuntime();

        String  url=mode.getValueAt(row, col).toString();
    
        
        
        
        
     
      if(!url.isEmpty()){
      
        rt.exec("rundll32 url.dll,FileProtocolHandler " +url);
      }
        
        
     
         
     }catch(IOException ex) {
     }
        
   
    

        
        
        
      }
    });

       tab.getColumn("Photo").setCellRenderer(new DefaultTableCellRenderer(){
   @Override
  public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
          DefaultTableCellRenderer r =(DefaultTableCellRenderer) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); //To change body of generated methods, choose Tools | Templates.
          if (column==6) {
              r.setForeground(Color.BLACK);
              String a =getText();
              setText("<html><u>"+a+"</u></html>");
          }
          
          
          
          
          return r;
      }      
   });

 
 
 
 
 
 
 
 tab.addMouseMotionListener(new MouseAdapter() {
    public void mouseMoved(MouseEvent e) 
    {
        int cModel = tab.columnAtPoint(e.getPoint());
        int cView = tab.convertColumnIndexToView(cModel);
        if (cView == 6)
        {
        tab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        }
        else
        {
        tab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }
    }
});
 
  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_idcmdclt = new javax.swing.JLabel();
        txt_idcmdclt = new javax.swing.JTextField();
        Rechercher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        Fermer = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_idcmdclt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_idcmdclt.setText("Identifiant de la commande du client : ");
        getContentPane().add(lb_idcmdclt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));
        getContentPane().add(txt_idcmdclt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 320, 30));

        Rechercher.setText("Rechercher");
        Rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherActionPerformed(evt);
            }
        });
        getContentPane().add(Rechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 150, 30));

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identifiant  Commande", "Identifiant du Client", "Avance Client Cmd", "Propriété 1", "Propriété 2", "Date", "Photo"
            }
        ));
        jScrollPane1.setViewportView(tab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 960, 200));

        Fermer.setText("Fermer");
        Fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FermerActionPerformed(evt);
            }
        });
        getContentPane().add(Fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 120, 30));

        Modifier.setText("Modifier");
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });
        getContentPane().add(Modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 120, 30));

        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(Supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PFE/GUI/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FermerActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_FermerActionPerformed

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
 
       int i = tab.getSelectedRow();

        
                 
        
        
                if(i >= 0){
                    // remove a row from jtable

                    IdCmdClt=mode.getValueAt(i,0).toString();
                    IdClt=mode.getValueAt(i,1).toString();
                    AvanceCmdClt=Double.parseDouble(mode.getValueAt(i,2).toString());
                    Prop1CmdClt=mode.getValueAt(i,3).toString();
                    Prop2CmdClt=mode.getValueAt(i,4).toString();
                    DateCmdClt=mode.getValueAt(i,5).toString();
                    PhotoCmdClt=mode.getValueAt(i,6).toString();

            new ajout_modif_cmd_clt(1, IdCmdClt, IdClt, AvanceCmdClt, Prop1CmdClt, Prop2CmdClt, DateCmdClt, PhotoCmdClt,"rech_cmd_clt1").setVisible(true);
            
           
                   
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                   
                     
                     
                     
                     
                }
                
        
        
        
        
        
        
        
        
        
        
        
          
        
        
        
        
        






// TODO add your handling code here:
    }//GEN-LAST:event_ModifierActionPerformed

    private void RechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherActionPerformed
        // TODO add your handling code here:
        
        
        
    if(txt_idcmdclt.getText().isEmpty()){txt_idcmdclt.setBorder(BorderFactory.createLineBorder(Color.red));}
    if(!txt_idcmdclt.getText().isEmpty()){txt_idcmdclt.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));
    AffichIdCmdClt(txt_idcmdclt.getText()); }
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_RechercherActionPerformed

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        // TODO add your handling code here:
        
        
        
             int i = tab.getSelectedRow();
                if(i >= 0){
                    // remove a row from jtable

                   String IdCmdClt=mode.getValueAt(i,0).toString();

                    JLabel message = new JLabel("Veuillez Supprimer Cette  Commande    ");
                    JLabel title = new JLabel("Message Information !");
                    UIManager.put("OptionPane.buttonFont",new Font("Times New Roman ",0,12));
                    message.setFont(new Font("Times New Roman", 0, 14));
                    title.setFont(new Font("Times New Roman", 0, 14));

                    if( JOptionPane.showConfirmDialog(null, message,title.getText(),JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){

                        
                        cmdclt.SuppCmdClt(IdCmdClt);
                        AffichIdCmdClt(IdCmdClt);
                    }

                }
               
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_SupprimerActionPerformed

    /**
     * @param IdCmdClt the command line arguments
     */
    
    public  static  void AffichIdCmdClt(String IdCmdClt){
       
       
       
       
       
       
       
    if(tr==0){
           
      CmdClt  cmdclt=new  CmdClt();
 
      if((cmdclt=cmdclt.RechIdCmdClt(IdCmdClt))!=null){
    
     row4_2[0]=cmdclt.getIdCmdClt();
     row4_2[1]=cmdclt.getIdClt();
     row4_2[2]=cmdclt.getAvanceCmdClt();
     row4_2[3]=cmdclt.getProp1CmdClt();
     row4_2[4]=cmdclt.getProp2CmdClt();
     row4_2[5]=cmdclt.getDateCmdClt();
     row4_2[6]=cmdclt.getTelecharger();
     
     
      mode.addRow(row4_2);
  
  
  
  
    if(mode.getRowCount()>=2){
  
       mode.removeRow(0);
   } 
     
   }else{
       
    mode.setRowCount(0);
        
   } 
   
  tr=1;
  return;
  }
    
    
    else if(tr==1){
        tr=0;
        mode.setRowCount(0);
        AffichIdCmdClt(IdCmdClt);
          }
   

     

   
   
   
   
   
   
       

      } 

    
    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rech_cmd_clt1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rech_cmd_clt1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rech_cmd_clt1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rech_cmd_clt1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rech_cmd_clt1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fermer;
    private javax.swing.JButton Modifier;
    private javax.swing.JButton Rechercher;
    private javax.swing.JButton Supprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_idcmdclt;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txt_idcmdclt;
    // End of variables declaration//GEN-END:variables
}
