/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PFE.GUI;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import static com.itextpdf.text.Element.ALIGN_MIDDLE;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import jxl.Workbook;
import jxl.format.Alignment;
import jxl.format.Border;
import jxl.format.BorderLineStyle;
import jxl.format.Colour;
import jxl.format.UnderlineStyle;
import jxl.format.VerticalAlignment;
import jxl.write.Label;
import jxl.write.WritableCellFormat;
import jxl.write.WritableFont;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;

/**
 *
 * @author MOHAMED
 */
public class updateclt extends javax.swing.JFrame {
     private  static Object[] row = new Object[7];
     private  static  DefaultTableModel  mode;   
     private  static   Clt  clt = new Clt();
     private  static int  tr=0;;  
     
   private String  IdClt;
   private String  NomClt;
   private String  Tel1Clt;
   private String  Tel2Clt;
   private String  Fax1Clt;
   private String  Fax2Clt;
   private String  AdrClt;   
   
     /**
     * Creates new form updateclt
     */
    public updateclt() {
        initComponents();
        mode=(DefaultTableModel)  tab.getModel();
        saisir.setBorder(BorderFactory.createLineBorder(new Color(76,41,211)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_critere = new javax.swing.JLabel();
        list_item = new javax.swing.JComboBox<>();
        saisir = new javax.swing.JTextField();
        Rechercher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        pdf = new javax.swing.JButton();
        excel = new javax.swing.JButton();
        fermer = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_critere.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_critere.setText("Critère de recherche : ");
        getContentPane().add(lb_critere, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        list_item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id Clt", "Nom Clt", "Toutes Clt" }));
        getContentPane().add(list_item, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 160, 30));
        getContentPane().add(saisir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 320, 30));

        Rechercher.setText("Rechercher");
        Rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherActionPerformed(evt);
            }
        });
        getContentPane().add(Rechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 140, 30));

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdClt", "NomClt", "Tel1Clt", "Tel2Clt", "Fax1Clt", "Fax2Clt", "AdrClt"
            }
        ));
        jScrollPane1.setViewportView(tab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 810, 180));

        pdf.setText("PDF");
        pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfActionPerformed(evt);
            }
        });
        getContentPane().add(pdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 90, 30));

        excel.setText("EXCEL");
        excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelActionPerformed(evt);
            }
        });
        getContentPane().add(excel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 90, 30));

        fermer.setText("Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });
        getContentPane().add(fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 120, 40));

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        getContentPane().add(modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 120, 40));

        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        getContentPane().add(supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PFE/GUI/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_fermerActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed


   int i = tab.getSelectedRow();

        
                 
        
        
                if(i >= 0){
                    // remove a row from jtable

                    IdClt=mode.getValueAt(i,0).toString();
                    NomClt=mode.getValueAt(i,1).toString();
                    Tel1Clt=mode.getValueAt(i,2).toString();
                    Tel2Clt=mode.getValueAt(i,3).toString();
                    Fax1Clt=mode.getValueAt(i,4).toString();
                    Fax2Clt=mode.getValueAt(i,5).toString();
                    AdrClt=mode.getValueAt(i,6).toString();

            ajout_modif_clt    a =  new ajout_modif_clt(1, IdClt, NomClt, Tel1Clt, Tel2Clt, Fax1Clt, Fax2Clt, AdrClt,(String) list_item.getSelectedItem(),saisir.getText());
            
            a.setVisible(true);
           
                   
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                   
                     
                     
                     
                     
                }
                
        
        
        
        
        











    }//GEN-LAST:event_modifierActionPerformed

    private void RechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherActionPerformed
        // TODO add your handling code here:
        
        
        
        
                String   choix=(String)list_item.getSelectedItem();

                
                
            if(!saisir.getText().isEmpty()){
                                  saisir.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));

                if(choix.equals("Id Clt")){
                    AffichIdClt(saisir.getText());                
                }else if(choix.equals("Nom Clt")){
                    AffichNomClt(saisir.getText());
                }}
            else if(choix.equals("Toutes Clt")){
                  saisir.setBorder(BorderFactory.createLineBorder(new Color(45,118,223)));

                    saisir.setText("");
                    AffichTousClt();
                }
        
            
            
            else{
                mode.setRowCount(0);
                saisir.setBorder(BorderFactory.createLineBorder(Color.RED));

            }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_RechercherActionPerformed

    private void pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfActionPerformed
        // TODO add your handling code here:
        
        
        
            
   if(mode.getRowCount()>=1){              
         try {
  Document document = new Document();
  
  
JFileChooser fileChooser = new JFileChooser();
fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
fileChooser.showOpenDialog(null);
File selectedFile = fileChooser.getSelectedFile();
String  file=selectedFile.getAbsolutePath();
if(!selectedFile.getAbsolutePath().endsWith(".pdf")){
 file=selectedFile.getAbsolutePath()+".pdf";  
}
  
  
 
  PdfWriter.getInstance(document, new FileOutputStream(file,true));
  document.open();
   float fntSize;
     fntSize = 10.0f;

  
 com.itextpdf.text.Image   image=com.itextpdf.text.Image.getInstance("C:\\Users\\HP\\Desktop\\Documents\\NetBeansProjects\\Acceuil\\src\\main\\images\\logo_4.png");
  image.setWidthPercentage(100);
  image.setAlignment(Element.ALIGN_LEFT);
  document.add(image);


  Paragraph   p3 =  new Paragraph("\n\n   Les Informations des  Clients      ", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.TIMES_ROMAN,14));
  p3.setAlignment(Element.ALIGN_CENTER);
  document.add(p3) ;
  
  


  PdfPTable table =  new PdfPTable(7);
  
  table.setWidthPercentage(105);
  table.setHorizontalAlignment(Element.ALIGN_BOTTOM);
  PdfPCell cel1;
  table.setWidths(new float[] { 68,70, 70,70, 70,70, 100 });
    com.itextpdf.text.Font font = FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.BOLD, BaseColor.WHITE);
    com.itextpdf.text.Font font2 = FontFactory.getFont(FontFactory.TIMES_ROMAN, fntSize);

    
    
    
    
    
    
    
    
            cel1 = new PdfPCell(new Phrase("Id Clt", font));
            cel1.setFixedHeight(20);
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
      
            
            
    
                       
            
            cel1 = new PdfPCell(new Phrase("Nom Clt", font));
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
            
           
            
            
            
            
            cel1 = new PdfPCell(new Phrase("N° Tel1 Clt", font));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
          
            
            
            cel1 = new PdfPCell(new Phrase("N° Tel1 Clt", font));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE); 
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
            
             cel1 = new PdfPCell(new Phrase("N° Fax1 Clt", font));
             cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
             cel1.setBackgroundColor(BaseColor.GRAY);
             cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cel1);
            
            
            cel1 = new PdfPCell(new Phrase("N° Fax Clt", font));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
            
            
            
            cel1 = new PdfPCell(new Phrase("Adresse Clt", font));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setBackgroundColor(BaseColor.GRAY);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);          
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
  
  
  
    String  ch =   (String) list_item.getSelectedItem();
    if(ch.equals("Id Clt")){

   Clt c=(Clt) clt.RechIdClt(saisir.getText());;
   if(c!=null){
   table.getDefaultCell().setVerticalAlignment(ALIGN_MIDDLE);
      
   
   
   
   
   
   
   
   
   
   
   
     cel1 = new PdfPCell(new Phrase(c.getIdClt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
          
   
   
              cel1 = new PdfPCell(new Phrase(c.getNomClt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
          
     
          
     cel1 = new PdfPCell(new Phrase(c.getTel1Clt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
          
     cel1 = new PdfPCell(new Phrase(c.getTel2Clt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
    cel1 = new PdfPCell(new Phrase(c.getFax1Clt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
   cel1 = new PdfPCell(new Phrase(c.getFax2Clt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
             
   
   cel1 = new PdfPCell(new Phrase(c.getAdrClt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
             
   
   
   
   
   
   
   
   
   
   
   
   
   

          JOptionPane.showMessageDialog(null, "PDF a éte enregistrer  ","Message Information",JOptionPane.INFORMATION_MESSAGE);

   }   
   

                    
                }
   
   
   else  if(ch.equals("Nom Clt")){
                    
      ArrayList <Clt>clts=clt.RechNomClt(saisir.getText());
     if(clts!=null){
      for(Clt  clt :  clts){
     
     
   
   
   
     cel1 = new PdfPCell(new Phrase(clt.getIdClt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
          
   
   
              cel1 = new PdfPCell(new Phrase(clt.getNomClt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
          
     cel1 = new PdfPCell(new Phrase(clt.getTel1Clt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
          
     cel1 = new PdfPCell(new Phrase(clt.getTel2Clt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
          
     cel1 = new PdfPCell(new Phrase(clt.getFax1Clt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
    cel1 = new PdfPCell(new Phrase(clt.getFax2Clt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);

             
   
   cel1 = new PdfPCell(new Phrase(clt.getAdrClt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
             
   
   
   
   
      
      
      
      
      
      
      }               
      JOptionPane.showMessageDialog(null, "PDF a éte enregistrer  ","Message Information",JOptionPane.INFORMATION_MESSAGE);
         
     }         



               
                
                
                
   }else {
                        
         
     ArrayList <Clt>list_clts=clt.RechTousClt();
     if(list_clts!=null){
      for(Clt  clt :  list_clts){
    
   
   
   
     cel1 = new PdfPCell(new Phrase(clt.getIdClt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
          
   
   
            cel1 = new PdfPCell(new Phrase(clt.getNomClt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
          
 
          
     cel1 = new PdfPCell(new Phrase(clt.getTel1Clt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
          
     cel1 = new PdfPCell(new Phrase(clt.getTel2Clt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
    cel1 = new PdfPCell(new Phrase(clt.getFax1Clt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
   cel1 = new PdfPCell(new Phrase(clt.getFax2Clt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
             
   
   cel1 = new PdfPCell(new Phrase(clt.getAdrClt(), font2));
            cel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cel1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cel1);
             
   
   
   
   
      }
         
         
                                  JOptionPane.showMessageDialog(null, "PDF a éte enregistrer  ","Message Information",JOptionPane.INFORMATION_MESSAGE);

         
         
         
                        }
 }
  
  
  
   
   
   
   
   
   
   
   

   
   
   
   
    document.add( new Phrase("\n") );

    document.add(table);
    document.add( Chunk.NEWLINE );

SimpleDateFormat simpleFormatter = new SimpleDateFormat("      '        ' dd/MM/yyyy  hh:mm:ss  ");
String date=simpleFormatter.format(new Date());
Paragraph  p2 = new Paragraph(date,FontFactory.getFont(FontFactory.TIMES_ROMAN,12));
 p2.setAlignment(Element.ALIGN_RIGHT);
 document.add(p2);

 

 
                    
                    
                    
                    
                    
                    
                    
                    
                    

                    
                    
  
  
  
  
  
  
  
    document.close();

  
  
} catch (Exception e) {
}        
                 
                 
                 
                 
                 
                 
                 
                  
                 
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
   }  
        
        
        
    }//GEN-LAST:event_pdfActionPerformed

    private void excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        
    
   
  if(mode.getRowCount()>=1){   
                 
    try {

 File selectedFile=null;       
JFileChooser fileChooser = new JFileChooser();
fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
fileChooser.showOpenDialog(null);
selectedFile = fileChooser.getSelectedFile();
if(selectedFile!=null){
    

 String  file=selectedFile.getAbsolutePath();
if(!selectedFile.getAbsolutePath().endsWith(".xls")){
 file=selectedFile.getAbsolutePath()+".xls";  
}
  
    WritableWorkbook workbook = Workbook.createWorkbook(new File(file));
    WritableSheet writablesheet1 = workbook.createSheet("Sheet1", 0);
    WritableFont times10pt = new WritableFont(WritableFont.TIMES, 12,WritableFont.BOLD);
    WritableFont times12pt = new WritableFont(WritableFont.TIMES, 11);
     int  rows =4;
   // Define the cell format
   WritableCellFormat  times = new WritableCellFormat(times10pt);
   WritableCellFormat  times2 = new WritableCellFormat(times12pt);
   times.setBorder(Border.ALL, BorderLineStyle.THIN, Colour.BLACK);
   times2.setBorder(Border.ALL, BorderLineStyle.THIN, Colour.BLACK);
  times.setBackground(Colour.WHITE);
  times.setAlignment(Alignment.CENTRE);
  times.setVerticalAlignment(VerticalAlignment.CENTRE);
   WritableCellFormat cellFormat = new WritableCellFormat(times);
    cellFormat.setBackground(Colour.YELLOW);
    cellFormat.setBorder(Border.ALL, BorderLineStyle.THIN);
   // Lets automatically wrap the cells
  // Create create a bold font with unterlines
   WritableFont times10ptBoldUnderline = new WritableFont(
   WritableFont.TIMES, 18, WritableFont.BOLD, false,
   UnderlineStyle.SINGLE);
   WritableCellFormat	timesBoldUnderline = new WritableCellFormat(times10ptBoldUnderline);
   // Lets automatically wrap the cells
Label label;
label = new Label(3, 1, "    La liste des Clients", timesBoldUnderline);
 writablesheet1.addCell(label);
    
    writablesheet1.setRowView(3, 26*20);
    writablesheet1.setColumnView(1,16);
    Label label1 = new Label(0,3,"Id Clt",cellFormat);
    writablesheet1.setColumnView(1, 28);
    Label label2 = new Label(1,3,"Nom Clt",cellFormat);
    writablesheet1.setColumnView(2, 25);
    Label label3 = new Label(2,3,"Numero Téléphone1 Clt",cellFormat);
    writablesheet1.setColumnView(3, 25);
    Label label4 = new Label(3,3,"Numero Téléphone2 Clt",cellFormat);
    writablesheet1.setColumnView(4, 25);
    Label label5 = new Label(4,3,"Numero Fax1 Clt",cellFormat);
    writablesheet1.setColumnView(5, 18);
    Label label6 = new Label(5,3,"Numero Fax2 Clt",cellFormat);
    writablesheet1.setColumnView(6, 40);
    Label label7 = new Label(6,3,"Adresse Clt",cellFormat);
   
    
    writablesheet1.addCell(label1);
    writablesheet1.addCell(label2);
    writablesheet1.addCell(label3);
    writablesheet1.addCell(label4);
    writablesheet1.addCell(label5);
    writablesheet1.addCell(label6);
    writablesheet1.addCell(label7);

    
    
        
        
        
    String  ch =   (String) list_item.getSelectedItem();
    if(ch.equals("Id Clt")){

   Clt c=clt.RechIdClt(saisir.getText());;
   if(clt!=null && tab.getRowCount()>=0){
  
   
       
     writablesheet1.addCell(new Label(0,4,c.getIdClt(),times2));
     writablesheet1.addCell(new Label(1,4,c.getNomClt(),times2));
     writablesheet1.addCell(new Label(2,4,c.getTel1Clt(),times2));
     writablesheet1.addCell(new Label(3,4,c.getTel2Clt(),times2));
     writablesheet1.addCell(new Label(4,4,c.getFax1Clt(),times2));
     writablesheet1.addCell(new Label(5,4,c.getFax2Clt(),times2));
     writablesheet1.addCell(new Label(6,4,c.getAdrClt(),times2));

       
       
       
       
       
       
                   rows=0;

   JOptionPane.showMessageDialog(null, "Excel a éte enregistrer  ","Message Information",JOptionPane.INFORMATION_MESSAGE);

   }   
   

                    
                }
 
    
    
    
    
    else  if(ch.equals("Nom Clt")){
    ArrayList <Clt>clts=clt.RechNomClt(saisir.getText());
      if(clts!=null && tab.getRowCount()>=1){
      for(Clt  clt:  clts){
     writablesheet1.setColumnView(0,16); 
     writablesheet1.addCell(new Label(0,rows,clt.getIdClt(),times2));
     writablesheet1.setColumnView(2,28);
     writablesheet1.addCell(new Label(1,rows,clt.getNomClt(),times2));
     writablesheet1.setColumnView(2,25);
     writablesheet1.addCell(new Label(2,rows,clt.getTel1Clt(),times2));
     writablesheet1.setColumnView(3,25);
     writablesheet1.addCell(new Label(3,rows,clt.getTel2Clt(),times2));
     writablesheet1.setColumnView(4,25);
     writablesheet1.addCell(new Label(4,rows,clt.getFax1Clt(),times2));
     writablesheet1.setColumnView(5,18);
     writablesheet1.addCell(new Label(5,rows,clt.getFax2Clt(),times2));
     writablesheet1.setColumnView(6,40);
     writablesheet1.addCell(new Label(6,rows,clt.getAdrClt(),times2));
    
       
      rows++;
      
      
      
      
      
      
      }  
                  rows=0;

      JOptionPane.showMessageDialog(null, "Excel a éte enregistrer  ","Message Information",JOptionPane.INFORMATION_MESSAGE);

     }         


                    
                }
                
                
                
                else {
                        
     ArrayList <Clt>clts=clt.RechTousClt();
     if(clts!=null && tab.getRowCount()>=1){
      for(Clt  clt:  clts){
     writablesheet1.setColumnView(0,16); 
     writablesheet1.addCell(new Label(0,rows,clt.getIdClt(),times2));
     writablesheet1.setColumnView(2,28);
     writablesheet1.addCell(new Label(1,rows,clt.getNomClt(),times2));
     writablesheet1.setColumnView(2,25);
     writablesheet1.addCell(new Label(2,rows,clt.getTel1Clt(),times2));
     writablesheet1.setColumnView(3,25);
     writablesheet1.addCell(new Label(3,rows,clt.getTel2Clt(),times2));
     writablesheet1.setColumnView(4,25);
     writablesheet1.addCell(new Label(4,rows,clt.getFax1Clt(),times2));
     writablesheet1.setColumnView(5,18);
     writablesheet1.addCell(new Label(5,rows,clt.getFax2Clt(),times2));
     writablesheet1.setColumnView(6,40);
     writablesheet1.addCell(new Label(6,rows,clt.getAdrClt(),times2));
    
       
      rows++;
      
      
      
      
      
      
      }  
                  rows=0;

      JOptionPane.showMessageDialog(null, "Excel a éte enregistrer  ","Message Information",JOptionPane.INFORMATION_MESSAGE);

     }         


 }
  
  
  
   
   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
     
    workbook.write();
    workbook.close();
    
}   
    
} catch (WriteException e) {
  JOptionPane.showMessageDialog(null, e);

}                catch (IOException ex) {        
                 }        
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
  
        
        
        
        
        
        
            
        
        
        
        
        
  }
        
        
        
        
    }//GEN-LAST:event_excelActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
        
        
        
        
          int i = tab.getSelectedRow();
                if(i >= 0){
                    // remove a row from jtable

                    IdClt=mode.getValueAt(i,0).toString();

                    JLabel message = new JLabel("Veuillez Supprimer Ce Fournisseur    ");
                    JLabel title = new JLabel("Message Information !");
                    UIManager.put("OptionPane.buttonFont",new Font("Times New Roman ",0,12));
                    message.setFont(new Font("Times New Roman", 0, 14));
                    title.setFont(new Font("Times New Roman", 0, 14));

                    if( JOptionPane.showConfirmDialog(null, message,title.getText(),JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){

                        clt.SuppClt(IdClt);
                        mode.removeRow(i);

                    }

                }
               
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_supprimerActionPerformed

   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param IdClt the command line arguments
     */
    
    
    
    
    
    
   public static void  AffichIdClt(String IdClt){
       
       
       
       
       
       
       
       if(tr==0){
           
      Clt   c =   new Clt();
 
   if((c=clt.RechIdClt(IdClt))!=null){
      
   row[0]=c.getIdClt();
   row[1]=c.getNomClt();
   row[2]=c.getTel1Clt();
   row[3]=c.getTel2Clt();
   row[4]=c.getFax1Clt();
   row[5]=c.getFax2Clt();
   row[6]=c.getAdrClt();
   mode.addRow(row);
  
    if(mode.getRowCount()>=2){
  
       mode.removeRow(0);
   } 
     
   }else{
     JLabel message = new JLabel("    IdClt  inexistant \n" );
     JLabel title = new JLabel("Message Information !");
     UIManager.put("OptionPane.okButtonText", " Oui");
     UIManager.put("OptionPane.buttonFont", new Font("Times New Roman ",0,12)); 
     JOptionPane.showMessageDialog(null, message.getText(),title.getText(),JOptionPane.INFORMATION_MESSAGE);
       
          
          
              mode.setRowCount(0);
        
   } 
   
  tr=1;
  return;
  }else if(tr==1){
        tr=0;
        mode.setRowCount(0);
        AffichIdClt(IdClt);
        
          }
   

     

   
   
   
   
   
   
       

      } 
   public static  void  AffichNomClt (String NomClt){
      ArrayList   <Clt>  Mylist = (clt.RechNomClt(NomClt));

 if(tr==0){

   if(clt.RechNomClt(NomClt)!=null){
   for(Clt    c: Mylist){   
   row[0]=c.getIdClt();
   row[1]=c.getNomClt();
   row[2]=c.getTel1Clt();
   row[3]=c.getTel2Clt();
   row[4]=c.getFax1Clt();
   row[5]=c.getFax2Clt();
   row[6]=c.getAdrClt();
   
   mode.addRow(row);
   }
  
   }else{
      JLabel message = new JLabel("    NomClt inexistant \n" );
     JLabel title = new JLabel("Message Information !");
     UIManager.put("OptionPane.okButtonText", " Oui");
     UIManager.put("OptionPane.buttonFont", new Font("Times New Roman ",0,12)); 
     JOptionPane.showMessageDialog(null, message.getText(),title.getText(),JOptionPane.INFORMATION_MESSAGE);
      mode.setRowCount(0);
   
   }       
   tr=1;    
    return ;
 }
 
 else if(tr==1){
        tr=0;
        mode.setRowCount(0);
        AffichNomClt(NomClt);
  
 }      
       
       
       
       
       
       
    
       
       
       
       
   }

   public static  void  AffichTousClt(){
         ArrayList   <Clt>  liste = clt.RechTousClt();

 if(tr==0){

   if((liste)!=null){
   for(Clt    c: liste){   
   row[0]=c.getIdClt();
   row[1]=c.getNomClt();
   row[2]=c.getTel1Clt();
   row[3]=c.getTel2Clt();
   row[4]=c.getFax1Clt();
   row[5]=c.getFax2Clt();
   row[6]=c.getAdrClt();

   mode.addRow(row);}
  
   }else{
   mode.setRowCount(0);
   
   }       
   tr=1;    
    return ;
 }
 
 else if(tr==1){
        tr=0;
        mode.setRowCount(0);
        AffichTousClt();
  
 }      
        
       
       
       
   }
    
    
    
    
    
    
    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateclt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateclt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateclt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateclt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateclt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Rechercher;
    private javax.swing.JButton excel;
    private javax.swing.JButton fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_critere;
    private javax.swing.JComboBox<String> list_item;
    private javax.swing.JButton modifier;
    private javax.swing.JButton pdf;
    private javax.swing.JTextField saisir;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
